// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Complex_Relational_Queries.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250405135241_mig_1")]
    partial class mig_1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Order 1",
                            PersonId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Order 2",
                            PersonId = 2
                        },
                        new
                        {
                            Id = 3,
                            Description = "Order 3",
                            PersonId = 3
                        },
                        new
                        {
                            Id = 4,
                            Description = "Order 4",
                            PersonId = 4
                        },
                        new
                        {
                            Id = 5,
                            Description = "Order 5",
                            PersonId = 5
                        },
                        new
                        {
                            Id = 6,
                            Description = "Order 6",
                            PersonId = 6
                        },
                        new
                        {
                            Id = 7,
                            Description = "Order 7",
                            PersonId = 7
                        },
                        new
                        {
                            Id = 8,
                            Description = "Order 8",
                            PersonId = 8
                        },
                        new
                        {
                            Id = 9,
                            Description = "Order 9",
                            PersonId = 9
                        },
                        new
                        {
                            Id = 10,
                            Description = "Order 10",
                            PersonId = 10
                        },
                        new
                        {
                            Id = 11,
                            Description = "Order 11",
                            PersonId = 11
                        },
                        new
                        {
                            Id = 12,
                            Description = "Order 12",
                            PersonId = 12
                        },
                        new
                        {
                            Id = 13,
                            Description = "Order 13",
                            PersonId = 13
                        },
                        new
                        {
                            Id = 14,
                            Description = "Order 14",
                            PersonId = 14
                        },
                        new
                        {
                            Id = 15,
                            Description = "Order 15",
                            PersonId = 15
                        },
                        new
                        {
                            Id = 16,
                            Description = "Order 16",
                            PersonId = 16
                        },
                        new
                        {
                            Id = 17,
                            Description = "Order 17",
                            PersonId = 17
                        },
                        new
                        {
                            Id = 18,
                            Description = "Order 18",
                            PersonId = 18
                        },
                        new
                        {
                            Id = 19,
                            Description = "Order 19",
                            PersonId = 19
                        },
                        new
                        {
                            Id = 20,
                            Description = "Order 20",
                            PersonId = 20
                        },
                        new
                        {
                            Id = 21,
                            Description = "Order 21",
                            PersonId = 21
                        },
                        new
                        {
                            Id = 22,
                            Description = "Order 22",
                            PersonId = 22
                        },
                        new
                        {
                            Id = 23,
                            Description = "Order 23",
                            PersonId = 23
                        },
                        new
                        {
                            Id = 24,
                            Description = "Order 24",
                            PersonId = 24
                        },
                        new
                        {
                            Id = 25,
                            Description = "Order 25",
                            PersonId = 25
                        },
                        new
                        {
                            Id = 26,
                            Description = "Order 26",
                            PersonId = 26
                        },
                        new
                        {
                            Id = 27,
                            Description = "Order 27",
                            PersonId = 27
                        },
                        new
                        {
                            Id = 28,
                            Description = "Order 28",
                            PersonId = 28
                        },
                        new
                        {
                            Id = 29,
                            Description = "Order 29",
                            PersonId = 29
                        },
                        new
                        {
                            Id = 30,
                            Description = "Order 30",
                            PersonId = 30
                        },
                        new
                        {
                            Id = 31,
                            Description = "Order 31",
                            PersonId = 31
                        },
                        new
                        {
                            Id = 32,
                            Description = "Order 32",
                            PersonId = 32
                        },
                        new
                        {
                            Id = 33,
                            Description = "Order 33",
                            PersonId = 33
                        },
                        new
                        {
                            Id = 34,
                            Description = "Order 34",
                            PersonId = 34
                        },
                        new
                        {
                            Id = 35,
                            Description = "Order 35",
                            PersonId = 35
                        },
                        new
                        {
                            Id = 36,
                            Description = "Order 36",
                            PersonId = 36
                        },
                        new
                        {
                            Id = 37,
                            Description = "Order 37",
                            PersonId = 37
                        },
                        new
                        {
                            Id = 38,
                            Description = "Order 38",
                            PersonId = 38
                        },
                        new
                        {
                            Id = 39,
                            Description = "Order 39",
                            PersonId = 39
                        },
                        new
                        {
                            Id = 40,
                            Description = "Order 40",
                            PersonId = 40
                        },
                        new
                        {
                            Id = 41,
                            Description = "Order 41",
                            PersonId = 41
                        },
                        new
                        {
                            Id = 42,
                            Description = "Order 42",
                            PersonId = 42
                        },
                        new
                        {
                            Id = 43,
                            Description = "Order 43",
                            PersonId = 43
                        },
                        new
                        {
                            Id = 44,
                            Description = "Order 44",
                            PersonId = 44
                        },
                        new
                        {
                            Id = 45,
                            Description = "Order 45",
                            PersonId = 45
                        },
                        new
                        {
                            Id = 46,
                            Description = "Order 46",
                            PersonId = 46
                        },
                        new
                        {
                            Id = 47,
                            Description = "Order 47",
                            PersonId = 47
                        },
                        new
                        {
                            Id = 48,
                            Description = "Order 48",
                            PersonId = 48
                        },
                        new
                        {
                            Id = 49,
                            Description = "Order 49",
                            PersonId = 49
                        },
                        new
                        {
                            Id = 50,
                            Description = "Order 50",
                            PersonId = 50
                        },
                        new
                        {
                            Id = 51,
                            Description = "Order 51",
                            PersonId = 51
                        },
                        new
                        {
                            Id = 52,
                            Description = "Order 52",
                            PersonId = 52
                        },
                        new
                        {
                            Id = 53,
                            Description = "Order 53",
                            PersonId = 53
                        },
                        new
                        {
                            Id = 54,
                            Description = "Order 54",
                            PersonId = 54
                        },
                        new
                        {
                            Id = 55,
                            Description = "Order 55",
                            PersonId = 55
                        },
                        new
                        {
                            Id = 56,
                            Description = "Order 56",
                            PersonId = 56
                        },
                        new
                        {
                            Id = 57,
                            Description = "Order 57",
                            PersonId = 57
                        },
                        new
                        {
                            Id = 58,
                            Description = "Order 58",
                            PersonId = 58
                        },
                        new
                        {
                            Id = 59,
                            Description = "Order 59",
                            PersonId = 59
                        },
                        new
                        {
                            Id = 60,
                            Description = "Order 60",
                            PersonId = 60
                        },
                        new
                        {
                            Id = 61,
                            Description = "Order 61",
                            PersonId = 61
                        },
                        new
                        {
                            Id = 62,
                            Description = "Order 62",
                            PersonId = 62
                        },
                        new
                        {
                            Id = 63,
                            Description = "Order 63",
                            PersonId = 63
                        },
                        new
                        {
                            Id = 64,
                            Description = "Order 64",
                            PersonId = 64
                        },
                        new
                        {
                            Id = 65,
                            Description = "Order 65",
                            PersonId = 65
                        },
                        new
                        {
                            Id = 66,
                            Description = "Order 66",
                            PersonId = 66
                        },
                        new
                        {
                            Id = 67,
                            Description = "Order 67",
                            PersonId = 67
                        },
                        new
                        {
                            Id = 68,
                            Description = "Order 68",
                            PersonId = 68
                        },
                        new
                        {
                            Id = 69,
                            Description = "Order 69",
                            PersonId = 69
                        },
                        new
                        {
                            Id = 70,
                            Description = "Order 70",
                            PersonId = 70
                        },
                        new
                        {
                            Id = 71,
                            Description = "Order 71",
                            PersonId = 71
                        },
                        new
                        {
                            Id = 72,
                            Description = "Order 72",
                            PersonId = 72
                        },
                        new
                        {
                            Id = 73,
                            Description = "Order 73",
                            PersonId = 73
                        },
                        new
                        {
                            Id = 74,
                            Description = "Order 74",
                            PersonId = 74
                        },
                        new
                        {
                            Id = 75,
                            Description = "Order 75",
                            PersonId = 75
                        },
                        new
                        {
                            Id = 76,
                            Description = "Order 76",
                            PersonId = 76
                        },
                        new
                        {
                            Id = 77,
                            Description = "Order 77",
                            PersonId = 77
                        },
                        new
                        {
                            Id = 78,
                            Description = "Order 78",
                            PersonId = 78
                        },
                        new
                        {
                            Id = 79,
                            Description = "Order 79",
                            PersonId = 79
                        },
                        new
                        {
                            Id = 80,
                            Description = "Order 80",
                            PersonId = 80
                        },
                        new
                        {
                            Id = 81,
                            Description = "Order 81",
                            PersonId = 81
                        },
                        new
                        {
                            Id = 82,
                            Description = "Order 82",
                            PersonId = 82
                        },
                        new
                        {
                            Id = 83,
                            Description = "Order 83",
                            PersonId = 83
                        },
                        new
                        {
                            Id = 84,
                            Description = "Order 84",
                            PersonId = 84
                        },
                        new
                        {
                            Id = 85,
                            Description = "Order 85",
                            PersonId = 85
                        },
                        new
                        {
                            Id = 86,
                            Description = "Order 86",
                            PersonId = 86
                        },
                        new
                        {
                            Id = 87,
                            Description = "Order 87",
                            PersonId = 87
                        },
                        new
                        {
                            Id = 88,
                            Description = "Order 88",
                            PersonId = 88
                        },
                        new
                        {
                            Id = 89,
                            Description = "Order 89",
                            PersonId = 89
                        },
                        new
                        {
                            Id = 90,
                            Description = "Order 90",
                            PersonId = 90
                        },
                        new
                        {
                            Id = 91,
                            Description = "Order 91",
                            PersonId = 91
                        },
                        new
                        {
                            Id = 92,
                            Description = "Order 92",
                            PersonId = 92
                        },
                        new
                        {
                            Id = 93,
                            Description = "Order 93",
                            PersonId = 93
                        },
                        new
                        {
                            Id = 94,
                            Description = "Order 94",
                            PersonId = 94
                        },
                        new
                        {
                            Id = 95,
                            Description = "Order 95",
                            PersonId = 95
                        },
                        new
                        {
                            Id = 96,
                            Description = "Order 96",
                            PersonId = 96
                        },
                        new
                        {
                            Id = 97,
                            Description = "Order 97",
                            PersonId = 97
                        },
                        new
                        {
                            Id = 98,
                            Description = "Order 98",
                            PersonId = 98
                        },
                        new
                        {
                            Id = 99,
                            Description = "Order 99",
                            PersonId = 99
                        },
                        new
                        {
                            Id = 100,
                            Description = "Order 100",
                            PersonId = 100
                        });
                });

            modelBuilder.Entity("Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Gender = 0,
                            Name = "Person 1"
                        },
                        new
                        {
                            Id = 2,
                            Gender = 0,
                            Name = "Person 2"
                        },
                        new
                        {
                            Id = 3,
                            Gender = 0,
                            Name = "Person 3"
                        },
                        new
                        {
                            Id = 4,
                            Gender = 0,
                            Name = "Person 4"
                        },
                        new
                        {
                            Id = 5,
                            Gender = 0,
                            Name = "Person 5"
                        },
                        new
                        {
                            Id = 6,
                            Gender = 0,
                            Name = "Person 6"
                        },
                        new
                        {
                            Id = 7,
                            Gender = 0,
                            Name = "Person 7"
                        },
                        new
                        {
                            Id = 8,
                            Gender = 0,
                            Name = "Person 8"
                        },
                        new
                        {
                            Id = 9,
                            Gender = 0,
                            Name = "Person 9"
                        },
                        new
                        {
                            Id = 10,
                            Gender = 0,
                            Name = "Person 10"
                        },
                        new
                        {
                            Id = 11,
                            Gender = 0,
                            Name = "Person 11"
                        },
                        new
                        {
                            Id = 12,
                            Gender = 0,
                            Name = "Person 12"
                        },
                        new
                        {
                            Id = 13,
                            Gender = 0,
                            Name = "Person 13"
                        },
                        new
                        {
                            Id = 14,
                            Gender = 0,
                            Name = "Person 14"
                        },
                        new
                        {
                            Id = 15,
                            Gender = 0,
                            Name = "Person 15"
                        },
                        new
                        {
                            Id = 16,
                            Gender = 0,
                            Name = "Person 16"
                        },
                        new
                        {
                            Id = 17,
                            Gender = 0,
                            Name = "Person 17"
                        },
                        new
                        {
                            Id = 18,
                            Gender = 0,
                            Name = "Person 18"
                        },
                        new
                        {
                            Id = 19,
                            Gender = 0,
                            Name = "Person 19"
                        },
                        new
                        {
                            Id = 20,
                            Gender = 0,
                            Name = "Person 20"
                        },
                        new
                        {
                            Id = 21,
                            Gender = 0,
                            Name = "Person 21"
                        },
                        new
                        {
                            Id = 22,
                            Gender = 0,
                            Name = "Person 22"
                        },
                        new
                        {
                            Id = 23,
                            Gender = 0,
                            Name = "Person 23"
                        },
                        new
                        {
                            Id = 24,
                            Gender = 0,
                            Name = "Person 24"
                        },
                        new
                        {
                            Id = 25,
                            Gender = 0,
                            Name = "Person 25"
                        },
                        new
                        {
                            Id = 26,
                            Gender = 0,
                            Name = "Person 26"
                        },
                        new
                        {
                            Id = 27,
                            Gender = 0,
                            Name = "Person 27"
                        },
                        new
                        {
                            Id = 28,
                            Gender = 0,
                            Name = "Person 28"
                        },
                        new
                        {
                            Id = 29,
                            Gender = 0,
                            Name = "Person 29"
                        },
                        new
                        {
                            Id = 30,
                            Gender = 0,
                            Name = "Person 30"
                        },
                        new
                        {
                            Id = 31,
                            Gender = 0,
                            Name = "Person 31"
                        },
                        new
                        {
                            Id = 32,
                            Gender = 0,
                            Name = "Person 32"
                        },
                        new
                        {
                            Id = 33,
                            Gender = 0,
                            Name = "Person 33"
                        },
                        new
                        {
                            Id = 34,
                            Gender = 0,
                            Name = "Person 34"
                        },
                        new
                        {
                            Id = 35,
                            Gender = 0,
                            Name = "Person 35"
                        },
                        new
                        {
                            Id = 36,
                            Gender = 0,
                            Name = "Person 36"
                        },
                        new
                        {
                            Id = 37,
                            Gender = 0,
                            Name = "Person 37"
                        },
                        new
                        {
                            Id = 38,
                            Gender = 0,
                            Name = "Person 38"
                        },
                        new
                        {
                            Id = 39,
                            Gender = 0,
                            Name = "Person 39"
                        },
                        new
                        {
                            Id = 40,
                            Gender = 0,
                            Name = "Person 40"
                        },
                        new
                        {
                            Id = 41,
                            Gender = 0,
                            Name = "Person 41"
                        },
                        new
                        {
                            Id = 42,
                            Gender = 0,
                            Name = "Person 42"
                        },
                        new
                        {
                            Id = 43,
                            Gender = 0,
                            Name = "Person 43"
                        },
                        new
                        {
                            Id = 44,
                            Gender = 0,
                            Name = "Person 44"
                        },
                        new
                        {
                            Id = 45,
                            Gender = 0,
                            Name = "Person 45"
                        },
                        new
                        {
                            Id = 46,
                            Gender = 0,
                            Name = "Person 46"
                        },
                        new
                        {
                            Id = 47,
                            Gender = 0,
                            Name = "Person 47"
                        },
                        new
                        {
                            Id = 48,
                            Gender = 0,
                            Name = "Person 48"
                        },
                        new
                        {
                            Id = 49,
                            Gender = 0,
                            Name = "Person 49"
                        },
                        new
                        {
                            Id = 50,
                            Gender = 0,
                            Name = "Person 50"
                        },
                        new
                        {
                            Id = 51,
                            Gender = 1,
                            Name = "Person 51"
                        },
                        new
                        {
                            Id = 52,
                            Gender = 1,
                            Name = "Person 52"
                        },
                        new
                        {
                            Id = 53,
                            Gender = 1,
                            Name = "Person 53"
                        },
                        new
                        {
                            Id = 54,
                            Gender = 1,
                            Name = "Person 54"
                        },
                        new
                        {
                            Id = 55,
                            Gender = 1,
                            Name = "Person 55"
                        },
                        new
                        {
                            Id = 56,
                            Gender = 1,
                            Name = "Person 56"
                        },
                        new
                        {
                            Id = 57,
                            Gender = 1,
                            Name = "Person 57"
                        },
                        new
                        {
                            Id = 58,
                            Gender = 1,
                            Name = "Person 58"
                        },
                        new
                        {
                            Id = 59,
                            Gender = 1,
                            Name = "Person 59"
                        },
                        new
                        {
                            Id = 60,
                            Gender = 1,
                            Name = "Person 60"
                        },
                        new
                        {
                            Id = 61,
                            Gender = 1,
                            Name = "Person 61"
                        },
                        new
                        {
                            Id = 62,
                            Gender = 1,
                            Name = "Person 62"
                        },
                        new
                        {
                            Id = 63,
                            Gender = 1,
                            Name = "Person 63"
                        },
                        new
                        {
                            Id = 64,
                            Gender = 1,
                            Name = "Person 64"
                        },
                        new
                        {
                            Id = 65,
                            Gender = 1,
                            Name = "Person 65"
                        },
                        new
                        {
                            Id = 66,
                            Gender = 1,
                            Name = "Person 66"
                        },
                        new
                        {
                            Id = 67,
                            Gender = 1,
                            Name = "Person 67"
                        },
                        new
                        {
                            Id = 68,
                            Gender = 1,
                            Name = "Person 68"
                        },
                        new
                        {
                            Id = 69,
                            Gender = 1,
                            Name = "Person 69"
                        },
                        new
                        {
                            Id = 70,
                            Gender = 1,
                            Name = "Person 70"
                        },
                        new
                        {
                            Id = 71,
                            Gender = 1,
                            Name = "Person 71"
                        },
                        new
                        {
                            Id = 72,
                            Gender = 1,
                            Name = "Person 72"
                        },
                        new
                        {
                            Id = 73,
                            Gender = 1,
                            Name = "Person 73"
                        },
                        new
                        {
                            Id = 74,
                            Gender = 1,
                            Name = "Person 74"
                        },
                        new
                        {
                            Id = 75,
                            Gender = 1,
                            Name = "Person 75"
                        },
                        new
                        {
                            Id = 76,
                            Gender = 1,
                            Name = "Person 76"
                        },
                        new
                        {
                            Id = 77,
                            Gender = 1,
                            Name = "Person 77"
                        },
                        new
                        {
                            Id = 78,
                            Gender = 1,
                            Name = "Person 78"
                        },
                        new
                        {
                            Id = 79,
                            Gender = 1,
                            Name = "Person 79"
                        },
                        new
                        {
                            Id = 80,
                            Gender = 1,
                            Name = "Person 80"
                        },
                        new
                        {
                            Id = 81,
                            Gender = 1,
                            Name = "Person 81"
                        },
                        new
                        {
                            Id = 82,
                            Gender = 1,
                            Name = "Person 82"
                        },
                        new
                        {
                            Id = 83,
                            Gender = 1,
                            Name = "Person 83"
                        },
                        new
                        {
                            Id = 84,
                            Gender = 1,
                            Name = "Person 84"
                        },
                        new
                        {
                            Id = 85,
                            Gender = 1,
                            Name = "Person 85"
                        },
                        new
                        {
                            Id = 86,
                            Gender = 1,
                            Name = "Person 86"
                        },
                        new
                        {
                            Id = 87,
                            Gender = 1,
                            Name = "Person 87"
                        },
                        new
                        {
                            Id = 88,
                            Gender = 1,
                            Name = "Person 88"
                        },
                        new
                        {
                            Id = 89,
                            Gender = 1,
                            Name = "Person 89"
                        },
                        new
                        {
                            Id = 90,
                            Gender = 1,
                            Name = "Person 90"
                        },
                        new
                        {
                            Id = 91,
                            Gender = 1,
                            Name = "Person 91"
                        },
                        new
                        {
                            Id = 92,
                            Gender = 1,
                            Name = "Person 92"
                        },
                        new
                        {
                            Id = 93,
                            Gender = 1,
                            Name = "Person 93"
                        },
                        new
                        {
                            Id = 94,
                            Gender = 1,
                            Name = "Person 94"
                        },
                        new
                        {
                            Id = 95,
                            Gender = 1,
                            Name = "Person 95"
                        },
                        new
                        {
                            Id = 96,
                            Gender = 1,
                            Name = "Person 96"
                        },
                        new
                        {
                            Id = 97,
                            Gender = 1,
                            Name = "Person 97"
                        },
                        new
                        {
                            Id = 98,
                            Gender = 1,
                            Name = "Person 98"
                        },
                        new
                        {
                            Id = 99,
                            Gender = 1,
                            Name = "Person 99"
                        },
                        new
                        {
                            Id = 100,
                            Gender = 1,
                            Name = "Person 100"
                        });
                });

            modelBuilder.Entity("Photo", b =>
                {
                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PersonId");

                    b.ToTable("Photos");

                    b.HasData(
                        new
                        {
                            PersonId = 1,
                            Url = "https://example.com/photo1.jpg"
                        },
                        new
                        {
                            PersonId = 2,
                            Url = "https://example.com/photo2.jpg"
                        },
                        new
                        {
                            PersonId = 3,
                            Url = "https://example.com/photo3.jpg"
                        },
                        new
                        {
                            PersonId = 4,
                            Url = "https://example.com/photo4.jpg"
                        },
                        new
                        {
                            PersonId = 5,
                            Url = "https://example.com/photo5.jpg"
                        },
                        new
                        {
                            PersonId = 6,
                            Url = "https://example.com/photo6.jpg"
                        },
                        new
                        {
                            PersonId = 7,
                            Url = "https://example.com/photo7.jpg"
                        },
                        new
                        {
                            PersonId = 8,
                            Url = "https://example.com/photo8.jpg"
                        },
                        new
                        {
                            PersonId = 9,
                            Url = "https://example.com/photo9.jpg"
                        },
                        new
                        {
                            PersonId = 10,
                            Url = "https://example.com/photo10.jpg"
                        },
                        new
                        {
                            PersonId = 11,
                            Url = "https://example.com/photo11.jpg"
                        },
                        new
                        {
                            PersonId = 12,
                            Url = "https://example.com/photo12.jpg"
                        },
                        new
                        {
                            PersonId = 13,
                            Url = "https://example.com/photo13.jpg"
                        },
                        new
                        {
                            PersonId = 14,
                            Url = "https://example.com/photo14.jpg"
                        },
                        new
                        {
                            PersonId = 15,
                            Url = "https://example.com/photo15.jpg"
                        },
                        new
                        {
                            PersonId = 16,
                            Url = "https://example.com/photo16.jpg"
                        },
                        new
                        {
                            PersonId = 17,
                            Url = "https://example.com/photo17.jpg"
                        },
                        new
                        {
                            PersonId = 18,
                            Url = "https://example.com/photo18.jpg"
                        },
                        new
                        {
                            PersonId = 19,
                            Url = "https://example.com/photo19.jpg"
                        },
                        new
                        {
                            PersonId = 20,
                            Url = "https://example.com/photo20.jpg"
                        },
                        new
                        {
                            PersonId = 21,
                            Url = "https://example.com/photo21.jpg"
                        },
                        new
                        {
                            PersonId = 22,
                            Url = "https://example.com/photo22.jpg"
                        },
                        new
                        {
                            PersonId = 23,
                            Url = "https://example.com/photo23.jpg"
                        },
                        new
                        {
                            PersonId = 24,
                            Url = "https://example.com/photo24.jpg"
                        },
                        new
                        {
                            PersonId = 25,
                            Url = "https://example.com/photo25.jpg"
                        },
                        new
                        {
                            PersonId = 26,
                            Url = "https://example.com/photo26.jpg"
                        },
                        new
                        {
                            PersonId = 27,
                            Url = "https://example.com/photo27.jpg"
                        },
                        new
                        {
                            PersonId = 28,
                            Url = "https://example.com/photo28.jpg"
                        },
                        new
                        {
                            PersonId = 29,
                            Url = "https://example.com/photo29.jpg"
                        },
                        new
                        {
                            PersonId = 30,
                            Url = "https://example.com/photo30.jpg"
                        },
                        new
                        {
                            PersonId = 31,
                            Url = "https://example.com/photo31.jpg"
                        },
                        new
                        {
                            PersonId = 32,
                            Url = "https://example.com/photo32.jpg"
                        },
                        new
                        {
                            PersonId = 33,
                            Url = "https://example.com/photo33.jpg"
                        },
                        new
                        {
                            PersonId = 34,
                            Url = "https://example.com/photo34.jpg"
                        },
                        new
                        {
                            PersonId = 35,
                            Url = "https://example.com/photo35.jpg"
                        },
                        new
                        {
                            PersonId = 36,
                            Url = "https://example.com/photo36.jpg"
                        },
                        new
                        {
                            PersonId = 37,
                            Url = "https://example.com/photo37.jpg"
                        },
                        new
                        {
                            PersonId = 38,
                            Url = "https://example.com/photo38.jpg"
                        },
                        new
                        {
                            PersonId = 39,
                            Url = "https://example.com/photo39.jpg"
                        },
                        new
                        {
                            PersonId = 40,
                            Url = "https://example.com/photo40.jpg"
                        },
                        new
                        {
                            PersonId = 41,
                            Url = "https://example.com/photo41.jpg"
                        },
                        new
                        {
                            PersonId = 42,
                            Url = "https://example.com/photo42.jpg"
                        },
                        new
                        {
                            PersonId = 43,
                            Url = "https://example.com/photo43.jpg"
                        },
                        new
                        {
                            PersonId = 44,
                            Url = "https://example.com/photo44.jpg"
                        },
                        new
                        {
                            PersonId = 45,
                            Url = "https://example.com/photo45.jpg"
                        },
                        new
                        {
                            PersonId = 46,
                            Url = "https://example.com/photo46.jpg"
                        },
                        new
                        {
                            PersonId = 47,
                            Url = "https://example.com/photo47.jpg"
                        },
                        new
                        {
                            PersonId = 48,
                            Url = "https://example.com/photo48.jpg"
                        },
                        new
                        {
                            PersonId = 49,
                            Url = "https://example.com/photo49.jpg"
                        },
                        new
                        {
                            PersonId = 50,
                            Url = "https://example.com/photo50.jpg"
                        },
                        new
                        {
                            PersonId = 51,
                            Url = "https://example.com/photo51.jpg"
                        },
                        new
                        {
                            PersonId = 52,
                            Url = "https://example.com/photo52.jpg"
                        },
                        new
                        {
                            PersonId = 53,
                            Url = "https://example.com/photo53.jpg"
                        },
                        new
                        {
                            PersonId = 54,
                            Url = "https://example.com/photo54.jpg"
                        },
                        new
                        {
                            PersonId = 55,
                            Url = "https://example.com/photo55.jpg"
                        },
                        new
                        {
                            PersonId = 56,
                            Url = "https://example.com/photo56.jpg"
                        },
                        new
                        {
                            PersonId = 57,
                            Url = "https://example.com/photo57.jpg"
                        },
                        new
                        {
                            PersonId = 58,
                            Url = "https://example.com/photo58.jpg"
                        },
                        new
                        {
                            PersonId = 59,
                            Url = "https://example.com/photo59.jpg"
                        },
                        new
                        {
                            PersonId = 60,
                            Url = "https://example.com/photo60.jpg"
                        },
                        new
                        {
                            PersonId = 61,
                            Url = "https://example.com/photo61.jpg"
                        },
                        new
                        {
                            PersonId = 62,
                            Url = "https://example.com/photo62.jpg"
                        },
                        new
                        {
                            PersonId = 63,
                            Url = "https://example.com/photo63.jpg"
                        },
                        new
                        {
                            PersonId = 64,
                            Url = "https://example.com/photo64.jpg"
                        },
                        new
                        {
                            PersonId = 65,
                            Url = "https://example.com/photo65.jpg"
                        },
                        new
                        {
                            PersonId = 66,
                            Url = "https://example.com/photo66.jpg"
                        },
                        new
                        {
                            PersonId = 67,
                            Url = "https://example.com/photo67.jpg"
                        },
                        new
                        {
                            PersonId = 68,
                            Url = "https://example.com/photo68.jpg"
                        },
                        new
                        {
                            PersonId = 69,
                            Url = "https://example.com/photo69.jpg"
                        },
                        new
                        {
                            PersonId = 70,
                            Url = "https://example.com/photo70.jpg"
                        },
                        new
                        {
                            PersonId = 71,
                            Url = "https://example.com/photo71.jpg"
                        },
                        new
                        {
                            PersonId = 72,
                            Url = "https://example.com/photo72.jpg"
                        },
                        new
                        {
                            PersonId = 73,
                            Url = "https://example.com/photo73.jpg"
                        },
                        new
                        {
                            PersonId = 74,
                            Url = "https://example.com/photo74.jpg"
                        },
                        new
                        {
                            PersonId = 75,
                            Url = "https://example.com/photo75.jpg"
                        },
                        new
                        {
                            PersonId = 76,
                            Url = "https://example.com/photo76.jpg"
                        },
                        new
                        {
                            PersonId = 77,
                            Url = "https://example.com/photo77.jpg"
                        },
                        new
                        {
                            PersonId = 78,
                            Url = "https://example.com/photo78.jpg"
                        },
                        new
                        {
                            PersonId = 79,
                            Url = "https://example.com/photo79.jpg"
                        },
                        new
                        {
                            PersonId = 80,
                            Url = "https://example.com/photo80.jpg"
                        },
                        new
                        {
                            PersonId = 81,
                            Url = "https://example.com/photo81.jpg"
                        },
                        new
                        {
                            PersonId = 82,
                            Url = "https://example.com/photo82.jpg"
                        },
                        new
                        {
                            PersonId = 83,
                            Url = "https://example.com/photo83.jpg"
                        },
                        new
                        {
                            PersonId = 84,
                            Url = "https://example.com/photo84.jpg"
                        },
                        new
                        {
                            PersonId = 85,
                            Url = "https://example.com/photo85.jpg"
                        },
                        new
                        {
                            PersonId = 86,
                            Url = "https://example.com/photo86.jpg"
                        },
                        new
                        {
                            PersonId = 87,
                            Url = "https://example.com/photo87.jpg"
                        },
                        new
                        {
                            PersonId = 88,
                            Url = "https://example.com/photo88.jpg"
                        },
                        new
                        {
                            PersonId = 89,
                            Url = "https://example.com/photo89.jpg"
                        },
                        new
                        {
                            PersonId = 90,
                            Url = "https://example.com/photo90.jpg"
                        },
                        new
                        {
                            PersonId = 91,
                            Url = "https://example.com/photo91.jpg"
                        },
                        new
                        {
                            PersonId = 92,
                            Url = "https://example.com/photo92.jpg"
                        },
                        new
                        {
                            PersonId = 93,
                            Url = "https://example.com/photo93.jpg"
                        },
                        new
                        {
                            PersonId = 94,
                            Url = "https://example.com/photo94.jpg"
                        },
                        new
                        {
                            PersonId = 95,
                            Url = "https://example.com/photo95.jpg"
                        },
                        new
                        {
                            PersonId = 96,
                            Url = "https://example.com/photo96.jpg"
                        },
                        new
                        {
                            PersonId = 97,
                            Url = "https://example.com/photo97.jpg"
                        },
                        new
                        {
                            PersonId = 98,
                            Url = "https://example.com/photo98.jpg"
                        },
                        new
                        {
                            PersonId = 99,
                            Url = "https://example.com/photo99.jpg"
                        },
                        new
                        {
                            PersonId = 100,
                            Url = "https://example.com/photo100.jpg"
                        });
                });

            modelBuilder.Entity("Order", b =>
                {
                    b.HasOne("Person", "Person")
                        .WithMany("Orders")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Photo", b =>
                {
                    b.HasOne("Person", "Person")
                        .WithOne("Photo")
                        .HasForeignKey("Photo", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Person", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Photo")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
