// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Loading_Related_Data_Eager_Loading.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250404090940_mig_1")]
    partial class mig_1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EmployeeId = 1,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            EmployeeId = 2,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            EmployeeId = 3,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            EmployeeId = 4,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            EmployeeId = 5,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            EmployeeId = 6,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            EmployeeId = 7,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            EmployeeId = 8,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            EmployeeId = 9,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            EmployeeId = 10,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            EmployeeId = 11,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            EmployeeId = 12,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            EmployeeId = 13,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 14,
                            EmployeeId = 14,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 15,
                            EmployeeId = 15,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 16,
                            EmployeeId = 16,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 17,
                            EmployeeId = 17,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 18,
                            EmployeeId = 18,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 19,
                            EmployeeId = 19,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 20,
                            EmployeeId = 20,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 21,
                            EmployeeId = 21,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 22,
                            EmployeeId = 22,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 23,
                            EmployeeId = 23,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 24,
                            EmployeeId = 24,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 25,
                            EmployeeId = 25,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 26,
                            EmployeeId = 26,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 27,
                            EmployeeId = 27,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 28,
                            EmployeeId = 28,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 29,
                            EmployeeId = 29,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 30,
                            EmployeeId = 30,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 31,
                            EmployeeId = 31,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 32,
                            EmployeeId = 32,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 33,
                            EmployeeId = 33,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 34,
                            EmployeeId = 34,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 35,
                            EmployeeId = 35,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 36,
                            EmployeeId = 36,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 37,
                            EmployeeId = 37,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 38,
                            EmployeeId = 38,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 39,
                            EmployeeId = 39,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 40,
                            EmployeeId = 40,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 41,
                            EmployeeId = 41,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 42,
                            EmployeeId = 42,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 43,
                            EmployeeId = 43,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 44,
                            EmployeeId = 44,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 45,
                            EmployeeId = 45,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 46,
                            EmployeeId = 46,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 47,
                            EmployeeId = 47,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 48,
                            EmployeeId = 48,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 49,
                            EmployeeId = 49,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 50,
                            EmployeeId = 50,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 51,
                            EmployeeId = 51,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 52,
                            EmployeeId = 52,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 53,
                            EmployeeId = 53,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 54,
                            EmployeeId = 54,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 55,
                            EmployeeId = 55,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 56,
                            EmployeeId = 56,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 57,
                            EmployeeId = 57,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 58,
                            EmployeeId = 58,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 59,
                            EmployeeId = 59,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 60,
                            EmployeeId = 60,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 61,
                            EmployeeId = 61,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 62,
                            EmployeeId = 62,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 63,
                            EmployeeId = 63,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 64,
                            EmployeeId = 64,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 65,
                            EmployeeId = 65,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 66,
                            EmployeeId = 66,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 67,
                            EmployeeId = 67,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 68,
                            EmployeeId = 68,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 69,
                            EmployeeId = 69,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 70,
                            EmployeeId = 70,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 71,
                            EmployeeId = 71,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 72,
                            EmployeeId = 72,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 73,
                            EmployeeId = 73,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 74,
                            EmployeeId = 74,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 75,
                            EmployeeId = 75,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 76,
                            EmployeeId = 76,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 77,
                            EmployeeId = 77,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 78,
                            EmployeeId = 78,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 79,
                            EmployeeId = 79,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 80,
                            EmployeeId = 80,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 81,
                            EmployeeId = 81,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 82,
                            EmployeeId = 82,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 83,
                            EmployeeId = 83,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 84,
                            EmployeeId = 84,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 85,
                            EmployeeId = 85,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 86,
                            EmployeeId = 86,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 87,
                            EmployeeId = 87,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 88,
                            EmployeeId = 88,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 89,
                            EmployeeId = 89,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 90,
                            EmployeeId = 90,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 91,
                            EmployeeId = 91,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 92,
                            EmployeeId = 92,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 93,
                            EmployeeId = 93,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 94,
                            EmployeeId = 94,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 95,
                            EmployeeId = 95,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 96,
                            EmployeeId = 96,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 97,
                            EmployeeId = 97,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 98,
                            EmployeeId = 98,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 99,
                            EmployeeId = 99,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 100,
                            EmployeeId = 100,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.HasKey("Id");

                    b.ToTable("Persons");

                    b.HasDiscriminator().HasValue("Person");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Region 1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Region 2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Region 3"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Region 4"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Region 5"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Region 6"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Region 7"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Region 8"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Region 9"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Region 10"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Region 11"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Region 12"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Region 13"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Region 14"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Region 15"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Region 16"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Region 17"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Region 18"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Region 19"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Region 20"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Region 21"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Region 22"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Region 23"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Region 24"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Region 25"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Region 26"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Region 27"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Region 28"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Region 29"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Region 30"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Region 31"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Region 32"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Region 33"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Region 34"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Region 35"
                        },
                        new
                        {
                            Id = 36,
                            Name = "Region 36"
                        },
                        new
                        {
                            Id = 37,
                            Name = "Region 37"
                        },
                        new
                        {
                            Id = 38,
                            Name = "Region 38"
                        },
                        new
                        {
                            Id = 39,
                            Name = "Region 39"
                        },
                        new
                        {
                            Id = 40,
                            Name = "Region 40"
                        },
                        new
                        {
                            Id = 41,
                            Name = "Region 41"
                        },
                        new
                        {
                            Id = 42,
                            Name = "Region 42"
                        },
                        new
                        {
                            Id = 43,
                            Name = "Region 43"
                        },
                        new
                        {
                            Id = 44,
                            Name = "Region 44"
                        },
                        new
                        {
                            Id = 45,
                            Name = "Region 45"
                        },
                        new
                        {
                            Id = 46,
                            Name = "Region 46"
                        },
                        new
                        {
                            Id = 47,
                            Name = "Region 47"
                        },
                        new
                        {
                            Id = 48,
                            Name = "Region 48"
                        },
                        new
                        {
                            Id = 49,
                            Name = "Region 49"
                        },
                        new
                        {
                            Id = 50,
                            Name = "Region 50"
                        },
                        new
                        {
                            Id = 51,
                            Name = "Region 51"
                        },
                        new
                        {
                            Id = 52,
                            Name = "Region 52"
                        },
                        new
                        {
                            Id = 53,
                            Name = "Region 53"
                        },
                        new
                        {
                            Id = 54,
                            Name = "Region 54"
                        },
                        new
                        {
                            Id = 55,
                            Name = "Region 55"
                        },
                        new
                        {
                            Id = 56,
                            Name = "Region 56"
                        },
                        new
                        {
                            Id = 57,
                            Name = "Region 57"
                        },
                        new
                        {
                            Id = 58,
                            Name = "Region 58"
                        },
                        new
                        {
                            Id = 59,
                            Name = "Region 59"
                        },
                        new
                        {
                            Id = 60,
                            Name = "Region 60"
                        },
                        new
                        {
                            Id = 61,
                            Name = "Region 61"
                        },
                        new
                        {
                            Id = 62,
                            Name = "Region 62"
                        },
                        new
                        {
                            Id = 63,
                            Name = "Region 63"
                        },
                        new
                        {
                            Id = 64,
                            Name = "Region 64"
                        },
                        new
                        {
                            Id = 65,
                            Name = "Region 65"
                        },
                        new
                        {
                            Id = 66,
                            Name = "Region 66"
                        },
                        new
                        {
                            Id = 67,
                            Name = "Region 67"
                        },
                        new
                        {
                            Id = 68,
                            Name = "Region 68"
                        },
                        new
                        {
                            Id = 69,
                            Name = "Region 69"
                        },
                        new
                        {
                            Id = 70,
                            Name = "Region 70"
                        },
                        new
                        {
                            Id = 71,
                            Name = "Region 71"
                        },
                        new
                        {
                            Id = 72,
                            Name = "Region 72"
                        },
                        new
                        {
                            Id = 73,
                            Name = "Region 73"
                        },
                        new
                        {
                            Id = 74,
                            Name = "Region 74"
                        },
                        new
                        {
                            Id = 75,
                            Name = "Region 75"
                        },
                        new
                        {
                            Id = 76,
                            Name = "Region 76"
                        },
                        new
                        {
                            Id = 77,
                            Name = "Region 77"
                        },
                        new
                        {
                            Id = 78,
                            Name = "Region 78"
                        },
                        new
                        {
                            Id = 79,
                            Name = "Region 79"
                        },
                        new
                        {
                            Id = 80,
                            Name = "Region 80"
                        },
                        new
                        {
                            Id = 81,
                            Name = "Region 81"
                        },
                        new
                        {
                            Id = 82,
                            Name = "Region 82"
                        },
                        new
                        {
                            Id = 83,
                            Name = "Region 83"
                        },
                        new
                        {
                            Id = 84,
                            Name = "Region 84"
                        },
                        new
                        {
                            Id = 85,
                            Name = "Region 85"
                        },
                        new
                        {
                            Id = 86,
                            Name = "Region 86"
                        },
                        new
                        {
                            Id = 87,
                            Name = "Region 87"
                        },
                        new
                        {
                            Id = 88,
                            Name = "Region 88"
                        },
                        new
                        {
                            Id = 89,
                            Name = "Region 89"
                        },
                        new
                        {
                            Id = 90,
                            Name = "Region 90"
                        },
                        new
                        {
                            Id = 91,
                            Name = "Region 91"
                        },
                        new
                        {
                            Id = 92,
                            Name = "Region 92"
                        },
                        new
                        {
                            Id = 93,
                            Name = "Region 93"
                        },
                        new
                        {
                            Id = 94,
                            Name = "Region 94"
                        },
                        new
                        {
                            Id = 95,
                            Name = "Region 95"
                        },
                        new
                        {
                            Id = 96,
                            Name = "Region 96"
                        },
                        new
                        {
                            Id = 97,
                            Name = "Region 97"
                        },
                        new
                        {
                            Id = 98,
                            Name = "Region 98"
                        },
                        new
                        {
                            Id = 99,
                            Name = "Region 99"
                        },
                        new
                        {
                            Id = 100,
                            Name = "Region 100"
                        });
                });

            modelBuilder.Entity("Employee", b =>
                {
                    b.HasBaseType("Person");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RegionId")
                        .HasColumnType("int");

                    b.Property<int>("Salary")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("RegionId");

                    b.HasDiscriminator().HasValue("Employee");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Ali 1",
                            RegionId = 1,
                            Salary = 1001,
                            Surname = "Veli 1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Ali 2",
                            RegionId = 2,
                            Salary = 1002,
                            Surname = "Veli 2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Ali 3",
                            RegionId = 3,
                            Salary = 1003,
                            Surname = "Veli 3"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Ali 4",
                            RegionId = 4,
                            Salary = 1004,
                            Surname = "Veli 4"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Ali 5",
                            RegionId = 5,
                            Salary = 1005,
                            Surname = "Veli 5"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Ali 6",
                            RegionId = 6,
                            Salary = 1006,
                            Surname = "Veli 6"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Ali 7",
                            RegionId = 7,
                            Salary = 1007,
                            Surname = "Veli 7"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Ali 8",
                            RegionId = 8,
                            Salary = 1008,
                            Surname = "Veli 8"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Ali 9",
                            RegionId = 9,
                            Salary = 1009,
                            Surname = "Veli 9"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Ali 10",
                            RegionId = 10,
                            Salary = 1010,
                            Surname = "Veli 10"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Ali 11",
                            RegionId = 11,
                            Salary = 1011,
                            Surname = "Veli 11"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Ali 12",
                            RegionId = 12,
                            Salary = 1012,
                            Surname = "Veli 12"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Ali 13",
                            RegionId = 13,
                            Salary = 1013,
                            Surname = "Veli 13"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Ali 14",
                            RegionId = 14,
                            Salary = 1014,
                            Surname = "Veli 14"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Ali 15",
                            RegionId = 15,
                            Salary = 1015,
                            Surname = "Veli 15"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Ali 16",
                            RegionId = 16,
                            Salary = 1016,
                            Surname = "Veli 16"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Ali 17",
                            RegionId = 17,
                            Salary = 1017,
                            Surname = "Veli 17"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Ali 18",
                            RegionId = 18,
                            Salary = 1018,
                            Surname = "Veli 18"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Ali 19",
                            RegionId = 19,
                            Salary = 1019,
                            Surname = "Veli 19"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Ali 20",
                            RegionId = 20,
                            Salary = 1020,
                            Surname = "Veli 20"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Ali 21",
                            RegionId = 21,
                            Salary = 1021,
                            Surname = "Veli 21"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Ali 22",
                            RegionId = 22,
                            Salary = 1022,
                            Surname = "Veli 22"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Ali 23",
                            RegionId = 23,
                            Salary = 1023,
                            Surname = "Veli 23"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Ali 24",
                            RegionId = 24,
                            Salary = 1024,
                            Surname = "Veli 24"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Ali 25",
                            RegionId = 25,
                            Salary = 1025,
                            Surname = "Veli 25"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Ali 26",
                            RegionId = 26,
                            Salary = 1026,
                            Surname = "Veli 26"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Ali 27",
                            RegionId = 27,
                            Salary = 1027,
                            Surname = "Veli 27"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Ali 28",
                            RegionId = 28,
                            Salary = 1028,
                            Surname = "Veli 28"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Ali 29",
                            RegionId = 29,
                            Salary = 1029,
                            Surname = "Veli 29"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Ali 30",
                            RegionId = 30,
                            Salary = 1030,
                            Surname = "Veli 30"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Ali 31",
                            RegionId = 31,
                            Salary = 1031,
                            Surname = "Veli 31"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Ali 32",
                            RegionId = 32,
                            Salary = 1032,
                            Surname = "Veli 32"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Ali 33",
                            RegionId = 33,
                            Salary = 1033,
                            Surname = "Veli 33"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Ali 34",
                            RegionId = 34,
                            Salary = 1034,
                            Surname = "Veli 34"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Ali 35",
                            RegionId = 35,
                            Salary = 1035,
                            Surname = "Veli 35"
                        },
                        new
                        {
                            Id = 36,
                            Name = "Ali 36",
                            RegionId = 36,
                            Salary = 1036,
                            Surname = "Veli 36"
                        },
                        new
                        {
                            Id = 37,
                            Name = "Ali 37",
                            RegionId = 37,
                            Salary = 1037,
                            Surname = "Veli 37"
                        },
                        new
                        {
                            Id = 38,
                            Name = "Ali 38",
                            RegionId = 38,
                            Salary = 1038,
                            Surname = "Veli 38"
                        },
                        new
                        {
                            Id = 39,
                            Name = "Ali 39",
                            RegionId = 39,
                            Salary = 1039,
                            Surname = "Veli 39"
                        },
                        new
                        {
                            Id = 40,
                            Name = "Ali 40",
                            RegionId = 40,
                            Salary = 1040,
                            Surname = "Veli 40"
                        },
                        new
                        {
                            Id = 41,
                            Name = "Ali 41",
                            RegionId = 41,
                            Salary = 1041,
                            Surname = "Veli 41"
                        },
                        new
                        {
                            Id = 42,
                            Name = "Ali 42",
                            RegionId = 42,
                            Salary = 1042,
                            Surname = "Veli 42"
                        },
                        new
                        {
                            Id = 43,
                            Name = "Ali 43",
                            RegionId = 43,
                            Salary = 1043,
                            Surname = "Veli 43"
                        },
                        new
                        {
                            Id = 44,
                            Name = "Ali 44",
                            RegionId = 44,
                            Salary = 1044,
                            Surname = "Veli 44"
                        },
                        new
                        {
                            Id = 45,
                            Name = "Ali 45",
                            RegionId = 45,
                            Salary = 1045,
                            Surname = "Veli 45"
                        },
                        new
                        {
                            Id = 46,
                            Name = "Ali 46",
                            RegionId = 46,
                            Salary = 1046,
                            Surname = "Veli 46"
                        },
                        new
                        {
                            Id = 47,
                            Name = "Ali 47",
                            RegionId = 47,
                            Salary = 1047,
                            Surname = "Veli 47"
                        },
                        new
                        {
                            Id = 48,
                            Name = "Ali 48",
                            RegionId = 48,
                            Salary = 1048,
                            Surname = "Veli 48"
                        },
                        new
                        {
                            Id = 49,
                            Name = "Ali 49",
                            RegionId = 49,
                            Salary = 1049,
                            Surname = "Veli 49"
                        },
                        new
                        {
                            Id = 50,
                            Name = "Ali 50",
                            RegionId = 50,
                            Salary = 1050,
                            Surname = "Veli 50"
                        },
                        new
                        {
                            Id = 51,
                            Name = "Ali 51",
                            RegionId = 51,
                            Salary = 1051,
                            Surname = "Veli 51"
                        },
                        new
                        {
                            Id = 52,
                            Name = "Ali 52",
                            RegionId = 52,
                            Salary = 1052,
                            Surname = "Veli 52"
                        },
                        new
                        {
                            Id = 53,
                            Name = "Ali 53",
                            RegionId = 53,
                            Salary = 1053,
                            Surname = "Veli 53"
                        },
                        new
                        {
                            Id = 54,
                            Name = "Ali 54",
                            RegionId = 54,
                            Salary = 1054,
                            Surname = "Veli 54"
                        },
                        new
                        {
                            Id = 55,
                            Name = "Ali 55",
                            RegionId = 55,
                            Salary = 1055,
                            Surname = "Veli 55"
                        },
                        new
                        {
                            Id = 56,
                            Name = "Ali 56",
                            RegionId = 56,
                            Salary = 1056,
                            Surname = "Veli 56"
                        },
                        new
                        {
                            Id = 57,
                            Name = "Ali 57",
                            RegionId = 57,
                            Salary = 1057,
                            Surname = "Veli 57"
                        },
                        new
                        {
                            Id = 58,
                            Name = "Ali 58",
                            RegionId = 58,
                            Salary = 1058,
                            Surname = "Veli 58"
                        },
                        new
                        {
                            Id = 59,
                            Name = "Ali 59",
                            RegionId = 59,
                            Salary = 1059,
                            Surname = "Veli 59"
                        },
                        new
                        {
                            Id = 60,
                            Name = "Ali 60",
                            RegionId = 60,
                            Salary = 1060,
                            Surname = "Veli 60"
                        },
                        new
                        {
                            Id = 61,
                            Name = "Ali 61",
                            RegionId = 61,
                            Salary = 1061,
                            Surname = "Veli 61"
                        },
                        new
                        {
                            Id = 62,
                            Name = "Ali 62",
                            RegionId = 62,
                            Salary = 1062,
                            Surname = "Veli 62"
                        },
                        new
                        {
                            Id = 63,
                            Name = "Ali 63",
                            RegionId = 63,
                            Salary = 1063,
                            Surname = "Veli 63"
                        },
                        new
                        {
                            Id = 64,
                            Name = "Ali 64",
                            RegionId = 64,
                            Salary = 1064,
                            Surname = "Veli 64"
                        },
                        new
                        {
                            Id = 65,
                            Name = "Ali 65",
                            RegionId = 65,
                            Salary = 1065,
                            Surname = "Veli 65"
                        },
                        new
                        {
                            Id = 66,
                            Name = "Ali 66",
                            RegionId = 66,
                            Salary = 1066,
                            Surname = "Veli 66"
                        },
                        new
                        {
                            Id = 67,
                            Name = "Ali 67",
                            RegionId = 67,
                            Salary = 1067,
                            Surname = "Veli 67"
                        },
                        new
                        {
                            Id = 68,
                            Name = "Ali 68",
                            RegionId = 68,
                            Salary = 1068,
                            Surname = "Veli 68"
                        },
                        new
                        {
                            Id = 69,
                            Name = "Ali 69",
                            RegionId = 69,
                            Salary = 1069,
                            Surname = "Veli 69"
                        },
                        new
                        {
                            Id = 70,
                            Name = "Ali 70",
                            RegionId = 70,
                            Salary = 1070,
                            Surname = "Veli 70"
                        },
                        new
                        {
                            Id = 71,
                            Name = "Ali 71",
                            RegionId = 71,
                            Salary = 1071,
                            Surname = "Veli 71"
                        },
                        new
                        {
                            Id = 72,
                            Name = "Ali 72",
                            RegionId = 72,
                            Salary = 1072,
                            Surname = "Veli 72"
                        },
                        new
                        {
                            Id = 73,
                            Name = "Ali 73",
                            RegionId = 73,
                            Salary = 1073,
                            Surname = "Veli 73"
                        },
                        new
                        {
                            Id = 74,
                            Name = "Ali 74",
                            RegionId = 74,
                            Salary = 1074,
                            Surname = "Veli 74"
                        },
                        new
                        {
                            Id = 75,
                            Name = "Ali 75",
                            RegionId = 75,
                            Salary = 1075,
                            Surname = "Veli 75"
                        },
                        new
                        {
                            Id = 76,
                            Name = "Ali 76",
                            RegionId = 76,
                            Salary = 1076,
                            Surname = "Veli 76"
                        },
                        new
                        {
                            Id = 77,
                            Name = "Ali 77",
                            RegionId = 77,
                            Salary = 1077,
                            Surname = "Veli 77"
                        },
                        new
                        {
                            Id = 78,
                            Name = "Ali 78",
                            RegionId = 78,
                            Salary = 1078,
                            Surname = "Veli 78"
                        },
                        new
                        {
                            Id = 79,
                            Name = "Ali 79",
                            RegionId = 79,
                            Salary = 1079,
                            Surname = "Veli 79"
                        },
                        new
                        {
                            Id = 80,
                            Name = "Ali 80",
                            RegionId = 80,
                            Salary = 1080,
                            Surname = "Veli 80"
                        },
                        new
                        {
                            Id = 81,
                            Name = "Ali 81",
                            RegionId = 81,
                            Salary = 1081,
                            Surname = "Veli 81"
                        },
                        new
                        {
                            Id = 82,
                            Name = "Ali 82",
                            RegionId = 82,
                            Salary = 1082,
                            Surname = "Veli 82"
                        },
                        new
                        {
                            Id = 83,
                            Name = "Ali 83",
                            RegionId = 83,
                            Salary = 1083,
                            Surname = "Veli 83"
                        },
                        new
                        {
                            Id = 84,
                            Name = "Ali 84",
                            RegionId = 84,
                            Salary = 1084,
                            Surname = "Veli 84"
                        },
                        new
                        {
                            Id = 85,
                            Name = "Ali 85",
                            RegionId = 85,
                            Salary = 1085,
                            Surname = "Veli 85"
                        },
                        new
                        {
                            Id = 86,
                            Name = "Ali 86",
                            RegionId = 86,
                            Salary = 1086,
                            Surname = "Veli 86"
                        },
                        new
                        {
                            Id = 87,
                            Name = "Ali 87",
                            RegionId = 87,
                            Salary = 1087,
                            Surname = "Veli 87"
                        },
                        new
                        {
                            Id = 88,
                            Name = "Ali 88",
                            RegionId = 88,
                            Salary = 1088,
                            Surname = "Veli 88"
                        },
                        new
                        {
                            Id = 89,
                            Name = "Ali 89",
                            RegionId = 89,
                            Salary = 1089,
                            Surname = "Veli 89"
                        },
                        new
                        {
                            Id = 90,
                            Name = "Ali 90",
                            RegionId = 90,
                            Salary = 1090,
                            Surname = "Veli 90"
                        },
                        new
                        {
                            Id = 91,
                            Name = "Ali 91",
                            RegionId = 91,
                            Salary = 1091,
                            Surname = "Veli 91"
                        },
                        new
                        {
                            Id = 92,
                            Name = "Ali 92",
                            RegionId = 92,
                            Salary = 1092,
                            Surname = "Veli 92"
                        },
                        new
                        {
                            Id = 93,
                            Name = "Ali 93",
                            RegionId = 93,
                            Salary = 1093,
                            Surname = "Veli 93"
                        },
                        new
                        {
                            Id = 94,
                            Name = "Ali 94",
                            RegionId = 94,
                            Salary = 1094,
                            Surname = "Veli 94"
                        },
                        new
                        {
                            Id = 95,
                            Name = "Ali 95",
                            RegionId = 95,
                            Salary = 1095,
                            Surname = "Veli 95"
                        },
                        new
                        {
                            Id = 96,
                            Name = "Ali 96",
                            RegionId = 96,
                            Salary = 1096,
                            Surname = "Veli 96"
                        },
                        new
                        {
                            Id = 97,
                            Name = "Ali 97",
                            RegionId = 97,
                            Salary = 1097,
                            Surname = "Veli 97"
                        },
                        new
                        {
                            Id = 98,
                            Name = "Ali 98",
                            RegionId = 98,
                            Salary = 1098,
                            Surname = "Veli 98"
                        },
                        new
                        {
                            Id = 99,
                            Name = "Ali 99",
                            RegionId = 99,
                            Salary = 1099,
                            Surname = "Veli 99"
                        },
                        new
                        {
                            Id = 100,
                            Name = "Ali 100",
                            RegionId = 100,
                            Salary = 1100,
                            Surname = "Veli 100"
                        });
                });

            modelBuilder.Entity("Order", b =>
                {
                    b.HasOne("Employee", "Employee")
                        .WithMany("Orders")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Employee", b =>
                {
                    b.HasOne("Region", "Region")
                        .WithMany("Employees")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("Region", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("Employee", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
