// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EF_Core_7_Entity_Splitting.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PostCode")
                        .HasColumnType("int");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Persons", (string)null);

                    b.SplitToTable("Addresses", null, t =>
                        {
                            t.Property("Id")
                                .HasColumnName("PersonId");

                            t.Property("City")
                                .HasColumnName("City");

                            t.Property("Country")
                                .HasColumnName("Country");

                            t.Property("PostCode")
                                .HasColumnName("PostCode");

                            t.Property("Street")
                                .HasColumnName("Street");
                        });

                    b.SplitToTable("PhoneNumbers", null, t =>
                        {
                            t.Property("Id")
                                .HasColumnName("PersonId");

                            t.Property("PhoneNumber")
                                .HasColumnName("PhoneNumber");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "City 1",
                            Country = "Country 1",
                            Name = "Person 1",
                            PhoneNumber = "Phone 1",
                            PostCode = 1,
                            Street = "Street 1",
                            Surname = "Surname 1"
                        },
                        new
                        {
                            Id = 2,
                            City = "City 2",
                            Country = "Country 2",
                            Name = "Person 2",
                            PhoneNumber = "Phone 2",
                            PostCode = 2,
                            Street = "Street 2",
                            Surname = "Surname 2"
                        },
                        new
                        {
                            Id = 3,
                            City = "City 3",
                            Country = "Country 3",
                            Name = "Person 3",
                            PhoneNumber = "Phone 3",
                            PostCode = 3,
                            Street = "Street 3",
                            Surname = "Surname 3"
                        },
                        new
                        {
                            Id = 4,
                            City = "City 4",
                            Country = "Country 4",
                            Name = "Person 4",
                            PhoneNumber = "Phone 4",
                            PostCode = 4,
                            Street = "Street 4",
                            Surname = "Surname 4"
                        },
                        new
                        {
                            Id = 5,
                            City = "City 5",
                            Country = "Country 5",
                            Name = "Person 5",
                            PhoneNumber = "Phone 5",
                            PostCode = 5,
                            Street = "Street 5",
                            Surname = "Surname 5"
                        },
                        new
                        {
                            Id = 6,
                            City = "City 6",
                            Country = "Country 6",
                            Name = "Person 6",
                            PhoneNumber = "Phone 6",
                            PostCode = 6,
                            Street = "Street 6",
                            Surname = "Surname 6"
                        },
                        new
                        {
                            Id = 7,
                            City = "City 7",
                            Country = "Country 7",
                            Name = "Person 7",
                            PhoneNumber = "Phone 7",
                            PostCode = 7,
                            Street = "Street 7",
                            Surname = "Surname 7"
                        },
                        new
                        {
                            Id = 8,
                            City = "City 8",
                            Country = "Country 8",
                            Name = "Person 8",
                            PhoneNumber = "Phone 8",
                            PostCode = 8,
                            Street = "Street 8",
                            Surname = "Surname 8"
                        },
                        new
                        {
                            Id = 9,
                            City = "City 9",
                            Country = "Country 9",
                            Name = "Person 9",
                            PhoneNumber = "Phone 9",
                            PostCode = 9,
                            Street = "Street 9",
                            Surname = "Surname 9"
                        },
                        new
                        {
                            Id = 10,
                            City = "City 10",
                            Country = "Country 10",
                            Name = "Person 10",
                            PhoneNumber = "Phone 10",
                            PostCode = 10,
                            Street = "Street 10",
                            Surname = "Surname 10"
                        },
                        new
                        {
                            Id = 11,
                            City = "City 11",
                            Country = "Country 11",
                            Name = "Person 11",
                            PhoneNumber = "Phone 11",
                            PostCode = 11,
                            Street = "Street 11",
                            Surname = "Surname 11"
                        },
                        new
                        {
                            Id = 12,
                            City = "City 12",
                            Country = "Country 12",
                            Name = "Person 12",
                            PhoneNumber = "Phone 12",
                            PostCode = 12,
                            Street = "Street 12",
                            Surname = "Surname 12"
                        },
                        new
                        {
                            Id = 13,
                            City = "City 13",
                            Country = "Country 13",
                            Name = "Person 13",
                            PhoneNumber = "Phone 13",
                            PostCode = 13,
                            Street = "Street 13",
                            Surname = "Surname 13"
                        },
                        new
                        {
                            Id = 14,
                            City = "City 14",
                            Country = "Country 14",
                            Name = "Person 14",
                            PhoneNumber = "Phone 14",
                            PostCode = 14,
                            Street = "Street 14",
                            Surname = "Surname 14"
                        },
                        new
                        {
                            Id = 15,
                            City = "City 15",
                            Country = "Country 15",
                            Name = "Person 15",
                            PhoneNumber = "Phone 15",
                            PostCode = 15,
                            Street = "Street 15",
                            Surname = "Surname 15"
                        },
                        new
                        {
                            Id = 16,
                            City = "City 16",
                            Country = "Country 16",
                            Name = "Person 16",
                            PhoneNumber = "Phone 16",
                            PostCode = 16,
                            Street = "Street 16",
                            Surname = "Surname 16"
                        },
                        new
                        {
                            Id = 17,
                            City = "City 17",
                            Country = "Country 17",
                            Name = "Person 17",
                            PhoneNumber = "Phone 17",
                            PostCode = 17,
                            Street = "Street 17",
                            Surname = "Surname 17"
                        },
                        new
                        {
                            Id = 18,
                            City = "City 18",
                            Country = "Country 18",
                            Name = "Person 18",
                            PhoneNumber = "Phone 18",
                            PostCode = 18,
                            Street = "Street 18",
                            Surname = "Surname 18"
                        },
                        new
                        {
                            Id = 19,
                            City = "City 19",
                            Country = "Country 19",
                            Name = "Person 19",
                            PhoneNumber = "Phone 19",
                            PostCode = 19,
                            Street = "Street 19",
                            Surname = "Surname 19"
                        },
                        new
                        {
                            Id = 20,
                            City = "City 20",
                            Country = "Country 20",
                            Name = "Person 20",
                            PhoneNumber = "Phone 20",
                            PostCode = 20,
                            Street = "Street 20",
                            Surname = "Surname 20"
                        },
                        new
                        {
                            Id = 21,
                            City = "City 21",
                            Country = "Country 21",
                            Name = "Person 21",
                            PhoneNumber = "Phone 21",
                            PostCode = 21,
                            Street = "Street 21",
                            Surname = "Surname 21"
                        },
                        new
                        {
                            Id = 22,
                            City = "City 22",
                            Country = "Country 22",
                            Name = "Person 22",
                            PhoneNumber = "Phone 22",
                            PostCode = 22,
                            Street = "Street 22",
                            Surname = "Surname 22"
                        },
                        new
                        {
                            Id = 23,
                            City = "City 23",
                            Country = "Country 23",
                            Name = "Person 23",
                            PhoneNumber = "Phone 23",
                            PostCode = 23,
                            Street = "Street 23",
                            Surname = "Surname 23"
                        },
                        new
                        {
                            Id = 24,
                            City = "City 24",
                            Country = "Country 24",
                            Name = "Person 24",
                            PhoneNumber = "Phone 24",
                            PostCode = 24,
                            Street = "Street 24",
                            Surname = "Surname 24"
                        },
                        new
                        {
                            Id = 25,
                            City = "City 25",
                            Country = "Country 25",
                            Name = "Person 25",
                            PhoneNumber = "Phone 25",
                            PostCode = 25,
                            Street = "Street 25",
                            Surname = "Surname 25"
                        },
                        new
                        {
                            Id = 26,
                            City = "City 26",
                            Country = "Country 26",
                            Name = "Person 26",
                            PhoneNumber = "Phone 26",
                            PostCode = 26,
                            Street = "Street 26",
                            Surname = "Surname 26"
                        },
                        new
                        {
                            Id = 27,
                            City = "City 27",
                            Country = "Country 27",
                            Name = "Person 27",
                            PhoneNumber = "Phone 27",
                            PostCode = 27,
                            Street = "Street 27",
                            Surname = "Surname 27"
                        },
                        new
                        {
                            Id = 28,
                            City = "City 28",
                            Country = "Country 28",
                            Name = "Person 28",
                            PhoneNumber = "Phone 28",
                            PostCode = 28,
                            Street = "Street 28",
                            Surname = "Surname 28"
                        },
                        new
                        {
                            Id = 29,
                            City = "City 29",
                            Country = "Country 29",
                            Name = "Person 29",
                            PhoneNumber = "Phone 29",
                            PostCode = 29,
                            Street = "Street 29",
                            Surname = "Surname 29"
                        },
                        new
                        {
                            Id = 30,
                            City = "City 30",
                            Country = "Country 30",
                            Name = "Person 30",
                            PhoneNumber = "Phone 30",
                            PostCode = 30,
                            Street = "Street 30",
                            Surname = "Surname 30"
                        },
                        new
                        {
                            Id = 31,
                            City = "City 31",
                            Country = "Country 31",
                            Name = "Person 31",
                            PhoneNumber = "Phone 31",
                            PostCode = 31,
                            Street = "Street 31",
                            Surname = "Surname 31"
                        },
                        new
                        {
                            Id = 32,
                            City = "City 32",
                            Country = "Country 32",
                            Name = "Person 32",
                            PhoneNumber = "Phone 32",
                            PostCode = 32,
                            Street = "Street 32",
                            Surname = "Surname 32"
                        },
                        new
                        {
                            Id = 33,
                            City = "City 33",
                            Country = "Country 33",
                            Name = "Person 33",
                            PhoneNumber = "Phone 33",
                            PostCode = 33,
                            Street = "Street 33",
                            Surname = "Surname 33"
                        },
                        new
                        {
                            Id = 34,
                            City = "City 34",
                            Country = "Country 34",
                            Name = "Person 34",
                            PhoneNumber = "Phone 34",
                            PostCode = 34,
                            Street = "Street 34",
                            Surname = "Surname 34"
                        },
                        new
                        {
                            Id = 35,
                            City = "City 35",
                            Country = "Country 35",
                            Name = "Person 35",
                            PhoneNumber = "Phone 35",
                            PostCode = 35,
                            Street = "Street 35",
                            Surname = "Surname 35"
                        },
                        new
                        {
                            Id = 36,
                            City = "City 36",
                            Country = "Country 36",
                            Name = "Person 36",
                            PhoneNumber = "Phone 36",
                            PostCode = 36,
                            Street = "Street 36",
                            Surname = "Surname 36"
                        },
                        new
                        {
                            Id = 37,
                            City = "City 37",
                            Country = "Country 37",
                            Name = "Person 37",
                            PhoneNumber = "Phone 37",
                            PostCode = 37,
                            Street = "Street 37",
                            Surname = "Surname 37"
                        },
                        new
                        {
                            Id = 38,
                            City = "City 38",
                            Country = "Country 38",
                            Name = "Person 38",
                            PhoneNumber = "Phone 38",
                            PostCode = 38,
                            Street = "Street 38",
                            Surname = "Surname 38"
                        },
                        new
                        {
                            Id = 39,
                            City = "City 39",
                            Country = "Country 39",
                            Name = "Person 39",
                            PhoneNumber = "Phone 39",
                            PostCode = 39,
                            Street = "Street 39",
                            Surname = "Surname 39"
                        },
                        new
                        {
                            Id = 40,
                            City = "City 40",
                            Country = "Country 40",
                            Name = "Person 40",
                            PhoneNumber = "Phone 40",
                            PostCode = 40,
                            Street = "Street 40",
                            Surname = "Surname 40"
                        },
                        new
                        {
                            Id = 41,
                            City = "City 41",
                            Country = "Country 41",
                            Name = "Person 41",
                            PhoneNumber = "Phone 41",
                            PostCode = 41,
                            Street = "Street 41",
                            Surname = "Surname 41"
                        },
                        new
                        {
                            Id = 42,
                            City = "City 42",
                            Country = "Country 42",
                            Name = "Person 42",
                            PhoneNumber = "Phone 42",
                            PostCode = 42,
                            Street = "Street 42",
                            Surname = "Surname 42"
                        },
                        new
                        {
                            Id = 43,
                            City = "City 43",
                            Country = "Country 43",
                            Name = "Person 43",
                            PhoneNumber = "Phone 43",
                            PostCode = 43,
                            Street = "Street 43",
                            Surname = "Surname 43"
                        },
                        new
                        {
                            Id = 44,
                            City = "City 44",
                            Country = "Country 44",
                            Name = "Person 44",
                            PhoneNumber = "Phone 44",
                            PostCode = 44,
                            Street = "Street 44",
                            Surname = "Surname 44"
                        },
                        new
                        {
                            Id = 45,
                            City = "City 45",
                            Country = "Country 45",
                            Name = "Person 45",
                            PhoneNumber = "Phone 45",
                            PostCode = 45,
                            Street = "Street 45",
                            Surname = "Surname 45"
                        },
                        new
                        {
                            Id = 46,
                            City = "City 46",
                            Country = "Country 46",
                            Name = "Person 46",
                            PhoneNumber = "Phone 46",
                            PostCode = 46,
                            Street = "Street 46",
                            Surname = "Surname 46"
                        },
                        new
                        {
                            Id = 47,
                            City = "City 47",
                            Country = "Country 47",
                            Name = "Person 47",
                            PhoneNumber = "Phone 47",
                            PostCode = 47,
                            Street = "Street 47",
                            Surname = "Surname 47"
                        },
                        new
                        {
                            Id = 48,
                            City = "City 48",
                            Country = "Country 48",
                            Name = "Person 48",
                            PhoneNumber = "Phone 48",
                            PostCode = 48,
                            Street = "Street 48",
                            Surname = "Surname 48"
                        },
                        new
                        {
                            Id = 49,
                            City = "City 49",
                            Country = "Country 49",
                            Name = "Person 49",
                            PhoneNumber = "Phone 49",
                            PostCode = 49,
                            Street = "Street 49",
                            Surname = "Surname 49"
                        },
                        new
                        {
                            Id = 50,
                            City = "City 50",
                            Country = "Country 50",
                            Name = "Person 50",
                            PhoneNumber = "Phone 50",
                            PostCode = 50,
                            Street = "Street 50",
                            Surname = "Surname 50"
                        },
                        new
                        {
                            Id = 51,
                            City = "City 51",
                            Country = "Country 51",
                            Name = "Person 51",
                            PhoneNumber = "Phone 51",
                            PostCode = 51,
                            Street = "Street 51",
                            Surname = "Surname 51"
                        },
                        new
                        {
                            Id = 52,
                            City = "City 52",
                            Country = "Country 52",
                            Name = "Person 52",
                            PhoneNumber = "Phone 52",
                            PostCode = 52,
                            Street = "Street 52",
                            Surname = "Surname 52"
                        },
                        new
                        {
                            Id = 53,
                            City = "City 53",
                            Country = "Country 53",
                            Name = "Person 53",
                            PhoneNumber = "Phone 53",
                            PostCode = 53,
                            Street = "Street 53",
                            Surname = "Surname 53"
                        },
                        new
                        {
                            Id = 54,
                            City = "City 54",
                            Country = "Country 54",
                            Name = "Person 54",
                            PhoneNumber = "Phone 54",
                            PostCode = 54,
                            Street = "Street 54",
                            Surname = "Surname 54"
                        },
                        new
                        {
                            Id = 55,
                            City = "City 55",
                            Country = "Country 55",
                            Name = "Person 55",
                            PhoneNumber = "Phone 55",
                            PostCode = 55,
                            Street = "Street 55",
                            Surname = "Surname 55"
                        },
                        new
                        {
                            Id = 56,
                            City = "City 56",
                            Country = "Country 56",
                            Name = "Person 56",
                            PhoneNumber = "Phone 56",
                            PostCode = 56,
                            Street = "Street 56",
                            Surname = "Surname 56"
                        },
                        new
                        {
                            Id = 57,
                            City = "City 57",
                            Country = "Country 57",
                            Name = "Person 57",
                            PhoneNumber = "Phone 57",
                            PostCode = 57,
                            Street = "Street 57",
                            Surname = "Surname 57"
                        },
                        new
                        {
                            Id = 58,
                            City = "City 58",
                            Country = "Country 58",
                            Name = "Person 58",
                            PhoneNumber = "Phone 58",
                            PostCode = 58,
                            Street = "Street 58",
                            Surname = "Surname 58"
                        },
                        new
                        {
                            Id = 59,
                            City = "City 59",
                            Country = "Country 59",
                            Name = "Person 59",
                            PhoneNumber = "Phone 59",
                            PostCode = 59,
                            Street = "Street 59",
                            Surname = "Surname 59"
                        },
                        new
                        {
                            Id = 60,
                            City = "City 60",
                            Country = "Country 60",
                            Name = "Person 60",
                            PhoneNumber = "Phone 60",
                            PostCode = 60,
                            Street = "Street 60",
                            Surname = "Surname 60"
                        },
                        new
                        {
                            Id = 61,
                            City = "City 61",
                            Country = "Country 61",
                            Name = "Person 61",
                            PhoneNumber = "Phone 61",
                            PostCode = 61,
                            Street = "Street 61",
                            Surname = "Surname 61"
                        },
                        new
                        {
                            Id = 62,
                            City = "City 62",
                            Country = "Country 62",
                            Name = "Person 62",
                            PhoneNumber = "Phone 62",
                            PostCode = 62,
                            Street = "Street 62",
                            Surname = "Surname 62"
                        },
                        new
                        {
                            Id = 63,
                            City = "City 63",
                            Country = "Country 63",
                            Name = "Person 63",
                            PhoneNumber = "Phone 63",
                            PostCode = 63,
                            Street = "Street 63",
                            Surname = "Surname 63"
                        },
                        new
                        {
                            Id = 64,
                            City = "City 64",
                            Country = "Country 64",
                            Name = "Person 64",
                            PhoneNumber = "Phone 64",
                            PostCode = 64,
                            Street = "Street 64",
                            Surname = "Surname 64"
                        },
                        new
                        {
                            Id = 65,
                            City = "City 65",
                            Country = "Country 65",
                            Name = "Person 65",
                            PhoneNumber = "Phone 65",
                            PostCode = 65,
                            Street = "Street 65",
                            Surname = "Surname 65"
                        },
                        new
                        {
                            Id = 66,
                            City = "City 66",
                            Country = "Country 66",
                            Name = "Person 66",
                            PhoneNumber = "Phone 66",
                            PostCode = 66,
                            Street = "Street 66",
                            Surname = "Surname 66"
                        },
                        new
                        {
                            Id = 67,
                            City = "City 67",
                            Country = "Country 67",
                            Name = "Person 67",
                            PhoneNumber = "Phone 67",
                            PostCode = 67,
                            Street = "Street 67",
                            Surname = "Surname 67"
                        },
                        new
                        {
                            Id = 68,
                            City = "City 68",
                            Country = "Country 68",
                            Name = "Person 68",
                            PhoneNumber = "Phone 68",
                            PostCode = 68,
                            Street = "Street 68",
                            Surname = "Surname 68"
                        },
                        new
                        {
                            Id = 69,
                            City = "City 69",
                            Country = "Country 69",
                            Name = "Person 69",
                            PhoneNumber = "Phone 69",
                            PostCode = 69,
                            Street = "Street 69",
                            Surname = "Surname 69"
                        },
                        new
                        {
                            Id = 70,
                            City = "City 70",
                            Country = "Country 70",
                            Name = "Person 70",
                            PhoneNumber = "Phone 70",
                            PostCode = 70,
                            Street = "Street 70",
                            Surname = "Surname 70"
                        },
                        new
                        {
                            Id = 71,
                            City = "City 71",
                            Country = "Country 71",
                            Name = "Person 71",
                            PhoneNumber = "Phone 71",
                            PostCode = 71,
                            Street = "Street 71",
                            Surname = "Surname 71"
                        },
                        new
                        {
                            Id = 72,
                            City = "City 72",
                            Country = "Country 72",
                            Name = "Person 72",
                            PhoneNumber = "Phone 72",
                            PostCode = 72,
                            Street = "Street 72",
                            Surname = "Surname 72"
                        },
                        new
                        {
                            Id = 73,
                            City = "City 73",
                            Country = "Country 73",
                            Name = "Person 73",
                            PhoneNumber = "Phone 73",
                            PostCode = 73,
                            Street = "Street 73",
                            Surname = "Surname 73"
                        },
                        new
                        {
                            Id = 74,
                            City = "City 74",
                            Country = "Country 74",
                            Name = "Person 74",
                            PhoneNumber = "Phone 74",
                            PostCode = 74,
                            Street = "Street 74",
                            Surname = "Surname 74"
                        },
                        new
                        {
                            Id = 75,
                            City = "City 75",
                            Country = "Country 75",
                            Name = "Person 75",
                            PhoneNumber = "Phone 75",
                            PostCode = 75,
                            Street = "Street 75",
                            Surname = "Surname 75"
                        },
                        new
                        {
                            Id = 76,
                            City = "City 76",
                            Country = "Country 76",
                            Name = "Person 76",
                            PhoneNumber = "Phone 76",
                            PostCode = 76,
                            Street = "Street 76",
                            Surname = "Surname 76"
                        },
                        new
                        {
                            Id = 77,
                            City = "City 77",
                            Country = "Country 77",
                            Name = "Person 77",
                            PhoneNumber = "Phone 77",
                            PostCode = 77,
                            Street = "Street 77",
                            Surname = "Surname 77"
                        },
                        new
                        {
                            Id = 78,
                            City = "City 78",
                            Country = "Country 78",
                            Name = "Person 78",
                            PhoneNumber = "Phone 78",
                            PostCode = 78,
                            Street = "Street 78",
                            Surname = "Surname 78"
                        },
                        new
                        {
                            Id = 79,
                            City = "City 79",
                            Country = "Country 79",
                            Name = "Person 79",
                            PhoneNumber = "Phone 79",
                            PostCode = 79,
                            Street = "Street 79",
                            Surname = "Surname 79"
                        },
                        new
                        {
                            Id = 80,
                            City = "City 80",
                            Country = "Country 80",
                            Name = "Person 80",
                            PhoneNumber = "Phone 80",
                            PostCode = 80,
                            Street = "Street 80",
                            Surname = "Surname 80"
                        },
                        new
                        {
                            Id = 81,
                            City = "City 81",
                            Country = "Country 81",
                            Name = "Person 81",
                            PhoneNumber = "Phone 81",
                            PostCode = 81,
                            Street = "Street 81",
                            Surname = "Surname 81"
                        },
                        new
                        {
                            Id = 82,
                            City = "City 82",
                            Country = "Country 82",
                            Name = "Person 82",
                            PhoneNumber = "Phone 82",
                            PostCode = 82,
                            Street = "Street 82",
                            Surname = "Surname 82"
                        },
                        new
                        {
                            Id = 83,
                            City = "City 83",
                            Country = "Country 83",
                            Name = "Person 83",
                            PhoneNumber = "Phone 83",
                            PostCode = 83,
                            Street = "Street 83",
                            Surname = "Surname 83"
                        },
                        new
                        {
                            Id = 84,
                            City = "City 84",
                            Country = "Country 84",
                            Name = "Person 84",
                            PhoneNumber = "Phone 84",
                            PostCode = 84,
                            Street = "Street 84",
                            Surname = "Surname 84"
                        },
                        new
                        {
                            Id = 85,
                            City = "City 85",
                            Country = "Country 85",
                            Name = "Person 85",
                            PhoneNumber = "Phone 85",
                            PostCode = 85,
                            Street = "Street 85",
                            Surname = "Surname 85"
                        },
                        new
                        {
                            Id = 86,
                            City = "City 86",
                            Country = "Country 86",
                            Name = "Person 86",
                            PhoneNumber = "Phone 86",
                            PostCode = 86,
                            Street = "Street 86",
                            Surname = "Surname 86"
                        },
                        new
                        {
                            Id = 87,
                            City = "City 87",
                            Country = "Country 87",
                            Name = "Person 87",
                            PhoneNumber = "Phone 87",
                            PostCode = 87,
                            Street = "Street 87",
                            Surname = "Surname 87"
                        },
                        new
                        {
                            Id = 88,
                            City = "City 88",
                            Country = "Country 88",
                            Name = "Person 88",
                            PhoneNumber = "Phone 88",
                            PostCode = 88,
                            Street = "Street 88",
                            Surname = "Surname 88"
                        },
                        new
                        {
                            Id = 89,
                            City = "City 89",
                            Country = "Country 89",
                            Name = "Person 89",
                            PhoneNumber = "Phone 89",
                            PostCode = 89,
                            Street = "Street 89",
                            Surname = "Surname 89"
                        },
                        new
                        {
                            Id = 90,
                            City = "City 90",
                            Country = "Country 90",
                            Name = "Person 90",
                            PhoneNumber = "Phone 90",
                            PostCode = 90,
                            Street = "Street 90",
                            Surname = "Surname 90"
                        },
                        new
                        {
                            Id = 91,
                            City = "City 91",
                            Country = "Country 91",
                            Name = "Person 91",
                            PhoneNumber = "Phone 91",
                            PostCode = 91,
                            Street = "Street 91",
                            Surname = "Surname 91"
                        },
                        new
                        {
                            Id = 92,
                            City = "City 92",
                            Country = "Country 92",
                            Name = "Person 92",
                            PhoneNumber = "Phone 92",
                            PostCode = 92,
                            Street = "Street 92",
                            Surname = "Surname 92"
                        },
                        new
                        {
                            Id = 93,
                            City = "City 93",
                            Country = "Country 93",
                            Name = "Person 93",
                            PhoneNumber = "Phone 93",
                            PostCode = 93,
                            Street = "Street 93",
                            Surname = "Surname 93"
                        },
                        new
                        {
                            Id = 94,
                            City = "City 94",
                            Country = "Country 94",
                            Name = "Person 94",
                            PhoneNumber = "Phone 94",
                            PostCode = 94,
                            Street = "Street 94",
                            Surname = "Surname 94"
                        },
                        new
                        {
                            Id = 95,
                            City = "City 95",
                            Country = "Country 95",
                            Name = "Person 95",
                            PhoneNumber = "Phone 95",
                            PostCode = 95,
                            Street = "Street 95",
                            Surname = "Surname 95"
                        },
                        new
                        {
                            Id = 96,
                            City = "City 96",
                            Country = "Country 96",
                            Name = "Person 96",
                            PhoneNumber = "Phone 96",
                            PostCode = 96,
                            Street = "Street 96",
                            Surname = "Surname 96"
                        },
                        new
                        {
                            Id = 97,
                            City = "City 97",
                            Country = "Country 97",
                            Name = "Person 97",
                            PhoneNumber = "Phone 97",
                            PostCode = 97,
                            Street = "Street 97",
                            Surname = "Surname 97"
                        },
                        new
                        {
                            Id = 98,
                            City = "City 98",
                            Country = "Country 98",
                            Name = "Person 98",
                            PhoneNumber = "Phone 98",
                            PostCode = 98,
                            Street = "Street 98",
                            Surname = "Surname 98"
                        },
                        new
                        {
                            Id = 99,
                            City = "City 99",
                            Country = "Country 99",
                            Name = "Person 99",
                            PhoneNumber = "Phone 99",
                            PostCode = 99,
                            Street = "Street 99",
                            Surname = "Surname 99"
                        },
                        new
                        {
                            Id = 100,
                            City = "City 100",
                            Country = "Country 100",
                            Name = "Person 100",
                            PhoneNumber = "Phone 100",
                            PostCode = 100,
                            Street = "Street 100",
                            Surname = "Surname 100"
                        });
                });

            modelBuilder.Entity("Person", b =>
                {
                    b.HasOne("Person", null)
                        .WithOne()
                        .HasForeignKey("Person", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
