// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EF_Core_Efficient_Querying.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Order 1",
                            PersonId = 1,
                            Price = 10
                        },
                        new
                        {
                            Id = 2,
                            Description = "Order 2",
                            PersonId = 2,
                            Price = 20
                        },
                        new
                        {
                            Id = 3,
                            Description = "Order 3",
                            PersonId = 3,
                            Price = 30
                        },
                        new
                        {
                            Id = 4,
                            Description = "Order 4",
                            PersonId = 4,
                            Price = 40
                        },
                        new
                        {
                            Id = 5,
                            Description = "Order 5",
                            PersonId = 5,
                            Price = 50
                        },
                        new
                        {
                            Id = 6,
                            Description = "Order 6",
                            PersonId = 6,
                            Price = 60
                        },
                        new
                        {
                            Id = 7,
                            Description = "Order 7",
                            PersonId = 7,
                            Price = 70
                        },
                        new
                        {
                            Id = 8,
                            Description = "Order 8",
                            PersonId = 8,
                            Price = 80
                        },
                        new
                        {
                            Id = 9,
                            Description = "Order 9",
                            PersonId = 9,
                            Price = 90
                        },
                        new
                        {
                            Id = 10,
                            Description = "Order 10",
                            PersonId = 10,
                            Price = 100
                        },
                        new
                        {
                            Id = 11,
                            Description = "Order 11",
                            PersonId = 11,
                            Price = 110
                        },
                        new
                        {
                            Id = 12,
                            Description = "Order 12",
                            PersonId = 12,
                            Price = 120
                        },
                        new
                        {
                            Id = 13,
                            Description = "Order 13",
                            PersonId = 13,
                            Price = 130
                        },
                        new
                        {
                            Id = 14,
                            Description = "Order 14",
                            PersonId = 14,
                            Price = 140
                        },
                        new
                        {
                            Id = 15,
                            Description = "Order 15",
                            PersonId = 15,
                            Price = 150
                        },
                        new
                        {
                            Id = 16,
                            Description = "Order 16",
                            PersonId = 16,
                            Price = 160
                        },
                        new
                        {
                            Id = 17,
                            Description = "Order 17",
                            PersonId = 17,
                            Price = 170
                        },
                        new
                        {
                            Id = 18,
                            Description = "Order 18",
                            PersonId = 18,
                            Price = 180
                        },
                        new
                        {
                            Id = 19,
                            Description = "Order 19",
                            PersonId = 19,
                            Price = 190
                        },
                        new
                        {
                            Id = 20,
                            Description = "Order 20",
                            PersonId = 20,
                            Price = 200
                        },
                        new
                        {
                            Id = 21,
                            Description = "Order 21",
                            PersonId = 21,
                            Price = 210
                        },
                        new
                        {
                            Id = 22,
                            Description = "Order 22",
                            PersonId = 22,
                            Price = 220
                        },
                        new
                        {
                            Id = 23,
                            Description = "Order 23",
                            PersonId = 23,
                            Price = 230
                        },
                        new
                        {
                            Id = 24,
                            Description = "Order 24",
                            PersonId = 24,
                            Price = 240
                        },
                        new
                        {
                            Id = 25,
                            Description = "Order 25",
                            PersonId = 25,
                            Price = 250
                        },
                        new
                        {
                            Id = 26,
                            Description = "Order 26",
                            PersonId = 26,
                            Price = 260
                        },
                        new
                        {
                            Id = 27,
                            Description = "Order 27",
                            PersonId = 27,
                            Price = 270
                        },
                        new
                        {
                            Id = 28,
                            Description = "Order 28",
                            PersonId = 28,
                            Price = 280
                        },
                        new
                        {
                            Id = 29,
                            Description = "Order 29",
                            PersonId = 29,
                            Price = 290
                        },
                        new
                        {
                            Id = 30,
                            Description = "Order 30",
                            PersonId = 30,
                            Price = 300
                        },
                        new
                        {
                            Id = 31,
                            Description = "Order 31",
                            PersonId = 31,
                            Price = 310
                        },
                        new
                        {
                            Id = 32,
                            Description = "Order 32",
                            PersonId = 32,
                            Price = 320
                        },
                        new
                        {
                            Id = 33,
                            Description = "Order 33",
                            PersonId = 33,
                            Price = 330
                        },
                        new
                        {
                            Id = 34,
                            Description = "Order 34",
                            PersonId = 34,
                            Price = 340
                        },
                        new
                        {
                            Id = 35,
                            Description = "Order 35",
                            PersonId = 35,
                            Price = 350
                        },
                        new
                        {
                            Id = 36,
                            Description = "Order 36",
                            PersonId = 36,
                            Price = 360
                        },
                        new
                        {
                            Id = 37,
                            Description = "Order 37",
                            PersonId = 37,
                            Price = 370
                        },
                        new
                        {
                            Id = 38,
                            Description = "Order 38",
                            PersonId = 38,
                            Price = 380
                        },
                        new
                        {
                            Id = 39,
                            Description = "Order 39",
                            PersonId = 39,
                            Price = 390
                        },
                        new
                        {
                            Id = 40,
                            Description = "Order 40",
                            PersonId = 40,
                            Price = 400
                        },
                        new
                        {
                            Id = 41,
                            Description = "Order 41",
                            PersonId = 41,
                            Price = 410
                        },
                        new
                        {
                            Id = 42,
                            Description = "Order 42",
                            PersonId = 42,
                            Price = 420
                        },
                        new
                        {
                            Id = 43,
                            Description = "Order 43",
                            PersonId = 43,
                            Price = 430
                        },
                        new
                        {
                            Id = 44,
                            Description = "Order 44",
                            PersonId = 44,
                            Price = 440
                        },
                        new
                        {
                            Id = 45,
                            Description = "Order 45",
                            PersonId = 45,
                            Price = 450
                        },
                        new
                        {
                            Id = 46,
                            Description = "Order 46",
                            PersonId = 46,
                            Price = 460
                        },
                        new
                        {
                            Id = 47,
                            Description = "Order 47",
                            PersonId = 47,
                            Price = 470
                        },
                        new
                        {
                            Id = 48,
                            Description = "Order 48",
                            PersonId = 48,
                            Price = 480
                        },
                        new
                        {
                            Id = 49,
                            Description = "Order 49",
                            PersonId = 49,
                            Price = 490
                        },
                        new
                        {
                            Id = 50,
                            Description = "Order 50",
                            PersonId = 50,
                            Price = 500
                        },
                        new
                        {
                            Id = 51,
                            Description = "Order 51",
                            PersonId = 51,
                            Price = 510
                        },
                        new
                        {
                            Id = 52,
                            Description = "Order 52",
                            PersonId = 52,
                            Price = 520
                        },
                        new
                        {
                            Id = 53,
                            Description = "Order 53",
                            PersonId = 53,
                            Price = 530
                        },
                        new
                        {
                            Id = 54,
                            Description = "Order 54",
                            PersonId = 54,
                            Price = 540
                        },
                        new
                        {
                            Id = 55,
                            Description = "Order 55",
                            PersonId = 55,
                            Price = 550
                        },
                        new
                        {
                            Id = 56,
                            Description = "Order 56",
                            PersonId = 56,
                            Price = 560
                        },
                        new
                        {
                            Id = 57,
                            Description = "Order 57",
                            PersonId = 57,
                            Price = 570
                        },
                        new
                        {
                            Id = 58,
                            Description = "Order 58",
                            PersonId = 58,
                            Price = 580
                        },
                        new
                        {
                            Id = 59,
                            Description = "Order 59",
                            PersonId = 59,
                            Price = 590
                        },
                        new
                        {
                            Id = 60,
                            Description = "Order 60",
                            PersonId = 60,
                            Price = 600
                        },
                        new
                        {
                            Id = 61,
                            Description = "Order 61",
                            PersonId = 61,
                            Price = 610
                        },
                        new
                        {
                            Id = 62,
                            Description = "Order 62",
                            PersonId = 62,
                            Price = 620
                        },
                        new
                        {
                            Id = 63,
                            Description = "Order 63",
                            PersonId = 63,
                            Price = 630
                        },
                        new
                        {
                            Id = 64,
                            Description = "Order 64",
                            PersonId = 64,
                            Price = 640
                        },
                        new
                        {
                            Id = 65,
                            Description = "Order 65",
                            PersonId = 65,
                            Price = 650
                        },
                        new
                        {
                            Id = 66,
                            Description = "Order 66",
                            PersonId = 66,
                            Price = 660
                        },
                        new
                        {
                            Id = 67,
                            Description = "Order 67",
                            PersonId = 67,
                            Price = 670
                        },
                        new
                        {
                            Id = 68,
                            Description = "Order 68",
                            PersonId = 68,
                            Price = 680
                        },
                        new
                        {
                            Id = 69,
                            Description = "Order 69",
                            PersonId = 69,
                            Price = 690
                        },
                        new
                        {
                            Id = 70,
                            Description = "Order 70",
                            PersonId = 70,
                            Price = 700
                        },
                        new
                        {
                            Id = 71,
                            Description = "Order 71",
                            PersonId = 71,
                            Price = 710
                        },
                        new
                        {
                            Id = 72,
                            Description = "Order 72",
                            PersonId = 72,
                            Price = 720
                        },
                        new
                        {
                            Id = 73,
                            Description = "Order 73",
                            PersonId = 73,
                            Price = 730
                        },
                        new
                        {
                            Id = 74,
                            Description = "Order 74",
                            PersonId = 74,
                            Price = 740
                        },
                        new
                        {
                            Id = 75,
                            Description = "Order 75",
                            PersonId = 75,
                            Price = 750
                        },
                        new
                        {
                            Id = 76,
                            Description = "Order 76",
                            PersonId = 76,
                            Price = 760
                        },
                        new
                        {
                            Id = 77,
                            Description = "Order 77",
                            PersonId = 77,
                            Price = 770
                        },
                        new
                        {
                            Id = 78,
                            Description = "Order 78",
                            PersonId = 78,
                            Price = 780
                        },
                        new
                        {
                            Id = 79,
                            Description = "Order 79",
                            PersonId = 79,
                            Price = 790
                        },
                        new
                        {
                            Id = 80,
                            Description = "Order 80",
                            PersonId = 80,
                            Price = 800
                        },
                        new
                        {
                            Id = 81,
                            Description = "Order 81",
                            PersonId = 81,
                            Price = 810
                        },
                        new
                        {
                            Id = 82,
                            Description = "Order 82",
                            PersonId = 82,
                            Price = 820
                        },
                        new
                        {
                            Id = 83,
                            Description = "Order 83",
                            PersonId = 83,
                            Price = 830
                        },
                        new
                        {
                            Id = 84,
                            Description = "Order 84",
                            PersonId = 84,
                            Price = 840
                        },
                        new
                        {
                            Id = 85,
                            Description = "Order 85",
                            PersonId = 85,
                            Price = 850
                        },
                        new
                        {
                            Id = 86,
                            Description = "Order 86",
                            PersonId = 86,
                            Price = 860
                        },
                        new
                        {
                            Id = 87,
                            Description = "Order 87",
                            PersonId = 87,
                            Price = 870
                        },
                        new
                        {
                            Id = 88,
                            Description = "Order 88",
                            PersonId = 88,
                            Price = 880
                        },
                        new
                        {
                            Id = 89,
                            Description = "Order 89",
                            PersonId = 89,
                            Price = 890
                        },
                        new
                        {
                            Id = 90,
                            Description = "Order 90",
                            PersonId = 90,
                            Price = 900
                        },
                        new
                        {
                            Id = 91,
                            Description = "Order 91",
                            PersonId = 91,
                            Price = 910
                        },
                        new
                        {
                            Id = 92,
                            Description = "Order 92",
                            PersonId = 92,
                            Price = 920
                        },
                        new
                        {
                            Id = 93,
                            Description = "Order 93",
                            PersonId = 93,
                            Price = 930
                        },
                        new
                        {
                            Id = 94,
                            Description = "Order 94",
                            PersonId = 94,
                            Price = 940
                        },
                        new
                        {
                            Id = 95,
                            Description = "Order 95",
                            PersonId = 95,
                            Price = 950
                        },
                        new
                        {
                            Id = 96,
                            Description = "Order 96",
                            PersonId = 96,
                            Price = 960
                        },
                        new
                        {
                            Id = 97,
                            Description = "Order 97",
                            PersonId = 97,
                            Price = 970
                        },
                        new
                        {
                            Id = 98,
                            Description = "Order 98",
                            PersonId = 98,
                            Price = 980
                        },
                        new
                        {
                            Id = 99,
                            Description = "Order 99",
                            PersonId = 99,
                            Price = 990
                        },
                        new
                        {
                            Id = 100,
                            Description = "Order 100",
                            PersonId = 100,
                            Price = 1000
                        });
                });

            modelBuilder.Entity("Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Person 1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Person 2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Person 3"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Person 4"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Person 5"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Person 6"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Person 7"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Person 8"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Person 9"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Person 10"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Person 11"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Person 12"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Person 13"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Person 14"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Person 15"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Person 16"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Person 17"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Person 18"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Person 19"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Person 20"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Person 21"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Person 22"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Person 23"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Person 24"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Person 25"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Person 26"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Person 27"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Person 28"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Person 29"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Person 30"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Person 31"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Person 32"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Person 33"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Person 34"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Person 35"
                        },
                        new
                        {
                            Id = 36,
                            Name = "Person 36"
                        },
                        new
                        {
                            Id = 37,
                            Name = "Person 37"
                        },
                        new
                        {
                            Id = 38,
                            Name = "Person 38"
                        },
                        new
                        {
                            Id = 39,
                            Name = "Person 39"
                        },
                        new
                        {
                            Id = 40,
                            Name = "Person 40"
                        },
                        new
                        {
                            Id = 41,
                            Name = "Person 41"
                        },
                        new
                        {
                            Id = 42,
                            Name = "Person 42"
                        },
                        new
                        {
                            Id = 43,
                            Name = "Person 43"
                        },
                        new
                        {
                            Id = 44,
                            Name = "Person 44"
                        },
                        new
                        {
                            Id = 45,
                            Name = "Person 45"
                        },
                        new
                        {
                            Id = 46,
                            Name = "Person 46"
                        },
                        new
                        {
                            Id = 47,
                            Name = "Person 47"
                        },
                        new
                        {
                            Id = 48,
                            Name = "Person 48"
                        },
                        new
                        {
                            Id = 49,
                            Name = "Person 49"
                        },
                        new
                        {
                            Id = 50,
                            Name = "Person 50"
                        },
                        new
                        {
                            Id = 51,
                            Name = "Person 51"
                        },
                        new
                        {
                            Id = 52,
                            Name = "Person 52"
                        },
                        new
                        {
                            Id = 53,
                            Name = "Person 53"
                        },
                        new
                        {
                            Id = 54,
                            Name = "Person 54"
                        },
                        new
                        {
                            Id = 55,
                            Name = "Person 55"
                        },
                        new
                        {
                            Id = 56,
                            Name = "Person 56"
                        },
                        new
                        {
                            Id = 57,
                            Name = "Person 57"
                        },
                        new
                        {
                            Id = 58,
                            Name = "Person 58"
                        },
                        new
                        {
                            Id = 59,
                            Name = "Person 59"
                        },
                        new
                        {
                            Id = 60,
                            Name = "Person 60"
                        },
                        new
                        {
                            Id = 61,
                            Name = "Person 61"
                        },
                        new
                        {
                            Id = 62,
                            Name = "Person 62"
                        },
                        new
                        {
                            Id = 63,
                            Name = "Person 63"
                        },
                        new
                        {
                            Id = 64,
                            Name = "Person 64"
                        },
                        new
                        {
                            Id = 65,
                            Name = "Person 65"
                        },
                        new
                        {
                            Id = 66,
                            Name = "Person 66"
                        },
                        new
                        {
                            Id = 67,
                            Name = "Person 67"
                        },
                        new
                        {
                            Id = 68,
                            Name = "Person 68"
                        },
                        new
                        {
                            Id = 69,
                            Name = "Person 69"
                        },
                        new
                        {
                            Id = 70,
                            Name = "Person 70"
                        },
                        new
                        {
                            Id = 71,
                            Name = "Person 71"
                        },
                        new
                        {
                            Id = 72,
                            Name = "Person 72"
                        },
                        new
                        {
                            Id = 73,
                            Name = "Person 73"
                        },
                        new
                        {
                            Id = 74,
                            Name = "Person 74"
                        },
                        new
                        {
                            Id = 75,
                            Name = "Person 75"
                        },
                        new
                        {
                            Id = 76,
                            Name = "Person 76"
                        },
                        new
                        {
                            Id = 77,
                            Name = "Person 77"
                        },
                        new
                        {
                            Id = 78,
                            Name = "Person 78"
                        },
                        new
                        {
                            Id = 79,
                            Name = "Person 79"
                        },
                        new
                        {
                            Id = 80,
                            Name = "Person 80"
                        },
                        new
                        {
                            Id = 81,
                            Name = "Person 81"
                        },
                        new
                        {
                            Id = 82,
                            Name = "Person 82"
                        },
                        new
                        {
                            Id = 83,
                            Name = "Person 83"
                        },
                        new
                        {
                            Id = 84,
                            Name = "Person 84"
                        },
                        new
                        {
                            Id = 85,
                            Name = "Person 85"
                        },
                        new
                        {
                            Id = 86,
                            Name = "Person 86"
                        },
                        new
                        {
                            Id = 87,
                            Name = "Person 87"
                        },
                        new
                        {
                            Id = 88,
                            Name = "Person 88"
                        },
                        new
                        {
                            Id = 89,
                            Name = "Person 89"
                        },
                        new
                        {
                            Id = 90,
                            Name = "Person 90"
                        },
                        new
                        {
                            Id = 91,
                            Name = "Person 91"
                        },
                        new
                        {
                            Id = 92,
                            Name = "Person 92"
                        },
                        new
                        {
                            Id = 93,
                            Name = "Person 93"
                        },
                        new
                        {
                            Id = 94,
                            Name = "Person 94"
                        },
                        new
                        {
                            Id = 95,
                            Name = "Person 95"
                        },
                        new
                        {
                            Id = 96,
                            Name = "Person 96"
                        },
                        new
                        {
                            Id = 97,
                            Name = "Person 97"
                        },
                        new
                        {
                            Id = 98,
                            Name = "Person 98"
                        },
                        new
                        {
                            Id = 99,
                            Name = "Person 99"
                        },
                        new
                        {
                            Id = 100,
                            Name = "Person 100"
                        });
                });

            modelBuilder.Entity("Order", b =>
                {
                    b.HasOne("Person", "Person")
                        .WithMany("Orders")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Person", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
